var MSG = {
    id_all_bright: "الكل ساطع",
    show_countdown: "عرض عدّ تنازلي",
    porject_alert_content: "عذرًا، معلمة خاطئة لتشغيل الهدف. برجاء التحقق!",
    sound_effects_popup_ok: "موافق",
    servo_speed: "السرعة",
    gyro_rotate_direction_popup_house: "زاوية إمالة",
    id_math_variables_set_add: "%1 + %2",
    help_title: "التعريف بالكتلة",
    servo_angle_popup_close: "إغلاق",
    id_show_show_emoji: "عرض الرموز التعبيرية",
    exit_popup_title: "نصائح",
    london_bridge: "أغنية 3",
    step_2: "خطوة 2",
    id_degree: "درجة",
    busy_tone: "نغمة مشغول",
    servo_angle_popup_title: "ضبط زاوية الدوران للمحرِّك",
    rotate_servo_popup_anti_clockwise: "عكس عقارب ساعة",
    long_lighton: "يعمل دائمًا",
    posture_set_desc: "افتح المفتاح الأيمن و قم بتعيين إجراء الآلي",
    recording_alert_ok: "موافق",
    porject_alert_content_02: "خطأ في تشغيل خدمة القاعدة. رسالة الخطأ",
    block_error_info: "يوجد خطأ في الكتلة الحالية، برجاء التحقق وإعادة المحاولة.",
    sound_effects_popup_cancel: "إلغاء ",
    id_close_eyes: "غلق العين",
    carhorn1: "مكبر صوت السيارة 1",
    id_fengshan: "مروحة",
    project_has_no_change: "لم يتم تغيير البرنامج الحالي",
    id_sensor_set_gyroscope: "تعيين جيروسكوب",
    servo_angle_popup_angle: "زاوية",
    id_show_play_effect: "تأثير تشغيل",
    sound_effects_recording_add: "إضافة تسجيل جديد",
    recording_tips: "تسجيل",
    id_control_break: "خارج الدورة",
    no_circle_servo_info: "لا يوجد معزِّز وضع العجلة حاليًا (يمكن التدوير حتى 360 درجة). هل تحتاج إلى إعداد واحد؟",
    recording: "تسجيل",
    run_msg: "!اسمح لـ Jimu للتحرك وفق البرمجة التي أجريتها به",
    id_control: "التحكم",
    variable_named_too_long: "يجب ألَّا يزيد اسم المشروع عن %1 من الحروف",
    movements: "الحركات",
    let_show_count: "عرض المؤقِّت مع أنبوب nixie",
    id_servos: "دوران محرِّك",
    recording_data_tips: "بدون تسجيلات",
    title_infrared_sensor: "ضبط مستشعر أشعة تحت حمراء",
    add_project_pop_title: "اسم المشروع",
    step_3: "خطوة 3",
    id_rotate: "دوران",
    trashTooltip: "تجاهل جميع الكتل.",
    id_smile: "ابتسامة",
    id_show_time_during: "لمدة",
    task: "مهمة",
    title_variable_set: "تعيين المتغير",
    id_control_wait_for: "انتظار حتى",
    z_axie: "زاوية تقدُّم",
    cheerful: "سعيد",
    id_to: "إلى",
    machine: "آلة",
    title_setting_tune: "نغمة الإعداد",
    surprise: "مفاجأة",
    badCode: "خطأ في البرنامج",
    dog: "كلب",
    no_project_tip: "لا يوجد مشروع، انقر على + في الركن العلوي الأيمن لإنشاء واحد!",
    id_daze: "مذهول",
    id_sensor_IR_sensor: "مستشعر IR",
    recording_ok: "موافق",
    infrared_tips: "النموذج الحالي غير متصل بمستشعر الأشعة تحت الحمراء",
    swift_msg: "!انقر هنا لعرض كود التحويل الإلكتروني",
    id_unlock: "فتح قفل",
    see_example: "عرض عينة",
    recording_name_popup_msg: "يحتوي اسم التسجيل على حروف غير صالحة",
    tiger: "نمر",
    variable_named_popup_placeholder: "المتغير",
    id_set: "تعيين",
    recording_popup_title: "إدخال اسم الملف المُسجَّل",
    police_car_1: "سيارة الشرطة 1",
    title_setting_light: "إضاءة الإعداد",
    servo_status_popup_tips: "يتعذر عليك ضبط المحرِّك المتوافق مع الآلي عندما يكون في وضع القفل",
    help_desc: "انقر هنا لعرض نصائح مفيدة عند حدوث مشكلة!",
    let_led_scenelight: "عرض ضوء المشهج مع أضواء LED",
    step_4: "خطوة 4",
    posture_named_popup_cancel: "إلغاء ",
    id_rotate_circle: "دوران محرِّك 360°",
    id_show: "عرض",
    speed_VS: "شديدة البطء",
    porject_alert_content_06: "تم حفظ المشروع",
    porject_alert_tips: "نصائح",
    id_in: "أثناء",
    telephone_call: "مكالمة هاتفية",
    recording_alert_title: "خطأ",
    ir_sensor: "مستشعر IR",
    id_sensor_reflectance_between_obstacle: "المسافة إلى عقبة",
    btn_name_confirm: "موافق",
    id_start: "ابدأ",
    id_show_scenelight: "إظهار عرض الأضواء",
    add_project_placeholder: "اسم المشروع",
    id_when_start: "انقر على \"تشغيل\" للبدء",
    yawn: "تثاءب",
    id_repeat: "تكرار",
    servo_status_popup_ok: "موافق",
    sealions: "أسد البحر",
    gyro_rotate_direction_popup_cancel: "إلغاء ",
    blocks: "الكتل",
    release: "تحرير",
    posture_link_popup_title: "توصيل النموذج",
    giraffe: "زرافة",
    recording_named_too_long: "يجب ألَّا يزيد اسم المشروع عن %1 من الحروف",
    title_setting_scenelight: "إعداد عرض الأضواء",
    touch_sensor: "مستشعر اللمس",
    catLists: "قوائم",
    id_actions: "تحركات",
    id_custom: "مخصص",
    support: "الدعم",
    servo_status_popup_title: "تعيين حالة المحرِّك",
    gyro_rotate_direction_popup_course: "زاوية تقدم",
    hashError: "عذرًا، '%1' لا يتطابق مع أيّ برنامج محفوظ.",
    recording_alert_content: "فشل منح الامتياز",
    id_huxi: "تنفس",
    shumaguan: "أنبوب Nixie",
    cow: "بقرة",
    textVariable: "نص",
    porject_alert_content_03: "خطأ في البيانات المستلمة من القاعدة!",
    doorbell: "جرس الباب",
    posture_named_popup_ok: "موافق",
    axie: "محور",
    show_number: "عرض الرقم",
    let_show_time: "عرض الوقت بوب nixie",
    move: "نقل",
    touch_tips: "النموذج الحالي غير متصل بمستشعر اللمس",
    gyroscope_tips: "النموذج الحالي غير متصل بمستشعر جيروسكوبي",
    id_run_to: "تشغيل على",
    project_pop_cancel_btn: "إلغاء ",
    tilt_up: "إمالة لأعلى",
    show_time: "عرض الوقت",
    posture_link_popup_cancel: "إلغاء",
    speed: "السرعة",
    robot: "روبوت",
    id_cry: "بكاء",
    exit_popup_ok: "موافق",
    id_jingya: "مندهش",
    id_shanshuo: "وميض",
    set_servo_mode: "الإعدادات",
    tilt_swing: "تحريك لإمالة",
    posture_link: "النموذج غير متصل. برجاء توصيل النموذج أولاً",
    id_control_wait: "انتظر",
    bear: "دب",
    select_all: "الكل",
    servo_direction: "الاتجاه",
    projectlist_msg: "!يمكنك عرض البرامج فقد تعلَّم Jimu البرامج الجديدة وأتقنها ويمكنه إنشاؤها لتنفيذ المهمة",
    input_rule_msg: "لا يمكن أن تبدأ رقما. يمكن إدخال %1 من الأحرف أو %2 من الأحرف الصينية كحد أقصى.",
    lights_tips: "النموذج الحالي غير متصل بأيّ ضوء",
    posture_link_popup_ok: "موافق",
    posture_named_popup_title: "تسمية الإجراء",
    laser: "الليزر",
    newProjectName: "مشروع جديد",
    title_device_tilt: "إعداد حالة هاتف/كمبيوتر لوحي",
    variable_named_popup_msg: "يتضمن اسم المتغير حروفًا غير صالحة",
    x_axie: "زاوية دحرجة",
    recording_title: "تسجيل",
    chicken: "دجاجة",
    title_bluetooth_connect: "توصيل Bluetooth",
    video_desc: "انقر هنا للاطلاع على فيديوهات وصف المهمة!",
    phone_pad: "هاتف/كمبيوتر لوحي",
    carhorn: "مكبر صوت السيارة",
    id_control_repeat: "تكرار",
    servo_angle_popup_cancel: "إلغاء ",
    id_show_play_tune: "نغمة التشغيل",
    let_stop_count: "وقف المؤقِّت مع أنبوب nixie",
    gyro_rotate_direction_popup_horizontal: "زاوية دحرجة",
    angry: "غاضب",
    id_millsecond: "م.ث",
    badXml: "خطأ في تحليل XML",
    gyro_rotate_direction_popup_curVal: "القيمة الحالية",
    id_show_time_ms: "م.ث",
    posture_named_popup_placeholder: "الإجراء",
    project_name_popup_msg: "يتضمن اسم المشروع حروفًا غير صالحة",
    porject_alert_btnText: "موافق",
    id_disco: "Disco",
    id_caise: "تداخل الألوان",
    title: "الكود",
    fail: "بالفشل",
    btn_name_cancel: "إلغاء",
    yankee_doodle: "أغنية 4",
    snoring: "الشخير",
    id_math_not: "غير",
    doubt: "سؤال",
    nonsense: "هذيان",
    bird: "طائر",
    speed_F: "سريعة",
    save_project_msg: "!انقر هنا لحفظ البرنامج",
    actingcute: "جذاب",
    speed_no_value: "طراز المحرِّك الحالي ليس به وضع دوران 360 .",
    recording_placeholder: "برجاء إدخال اسم تسجيل",
    servo_status_popup_locking: "قفل",
    walrus: "فظ البحر",
    help_msg: "!انقر هنا إذا كان لديك أسئلة",
    is_add_project_pop_tips: "هل تريد حفظ مشروع حالي؟",
    servo_angle_popup_ok: "موافق",
    catText: "نص",
    servo_status_popup_cancel: "إلغاء ",
    linkAlert: "مشاركة الكتل باستخدام هذا الرابط",
    id_sanyuanse: "الألوان الرئيسية",
    porject_alert_title: "خطأ",
    id_yugua: "ماسحات",
    id_math: "حساب",
    id_relei: "دموع",
    received: "تسلم",
    add_recording_ok: "موافق",
    current_value: "القيمة الحالية",
    engine: "المحرك",
    id_deng: "7 أضواء ملونة",
    porject_alert_content_04: "فشلت قراءة المشروع",
    gyroscope: "جيروسكوب",
    transfiguration: "تحول",
    id_sad: "حزين",
    project_name_too_long: "يجب ألَّا يزيد اسم المشروع عن %1 من الحروف",
    id_all: "الكل",
    posture_named_popup_msg: "يحتوي اسم الإجراء على حروف غير صالحة",
    title_touch_sensor: "ضبط مستشعر اللمس",
    id_moves: "تحركات",
    id_fadai: "مذهول",
    posture_named_too_long: "يجب ألَّا يزيد اسم الإجراء على %1 من الحروف",
    sound_effects_popup_title: "تعيين تأثيرات الصوت",
    rotate_servo_popup_title: "وضع الدوران",
    command: "أمر",
    id_show_show_LEDs: "عرض مؤشرات LED",
    id_sensors: "مستشعرات",
    let_show_number: "عرض الرقم مع أنبوب nixie",
    cover: "درع",
    go_skip: "تخطي",
    id_show_times: "مرات",
    course_tips: "يتعذر العرض الآن!",
    maincontrol_box: "صندوق تحكم أساسي",
    id_while: "بينما",
    xmlError: "تعذّر تحميل الملف المحفوظ. هل من المحتمل أنه تم إنشاؤه باستخدام إصدار مختلف من Blockly؟",
    police_car_2: "سيارة الشرطة 2",
    is_add_project_pop_title: "حفظ المشروع",
    tilt_right: "إمالة لليمين",
    set_countdown: "إعداد العدّ التنازلي",
    rotate_servo_popup_stop: "إيقاف",
    id_until: "حتى",
    index_back: "رجوع",
    id_blue_disconnect: "Bluetooth غير متصل",
    touch_tips_error: "رقم المنع الحالي غير صحيح، الرجاء حذفها وإعادة",
    catLogic: "المنطق",
    id_sensor_gyroscope: "جيروسكوب",
    animal: "حيوان",
    status: "الحالة هي",
    catMath: "حساب",
    recording_cancel: "إلغاء ",
    speed_M: "متوسطة",
    speed_only_360_value: "لا يحتوي الجهاز الحالي على محرِّك وضع الزاوية",
    id_control_seconds: "م.ث",
    gyro_rotate_direction_popup_title: "تحديد اتجاه الدوران لمحرك المعزّز",
    happy: "السعيدة",
    catLoops: "حلقات",
    id_open_eyes: "افتح عينيك",
    servo: "محرِّك",
    course_show: "عرض",
    id_ok: "موافق",
    title_time_adjust: "ضبط الوقت",
    porject_alert_content_01: "اسم العنصر موجود بالفعل. برجاء الإدخال مرة أخرى.",
    meebot: "meebot",
    timeout: "الحد الأقصى لتكرارات التنفيذ التي تم تجاوزها.",
    project_list_title: "مشروعاتي",
    rotate_servo_popup_clockwise: "كعقارب ساعة",
    close_blue: "Bluetooth غير متصل، فهل الاتصال مقطوع؟",
    wave: "تلويح",
    lion: "أسد",
    click: "النقر",
    id_leiguang: "دموع وامضة",
    id_lock: "قفل",
    elephant: "فيل",
    exit_popup_cancel: "إلغاء ",
    complete: "اكتمال",
    stop_count: "وقف المؤقِّت",
    low_power: "طاقة منخفضة",
    id_dizzy: "مصاب بدوار",
    rotate_servo_popup_ok: "موافق",
    rotate_servo_popup_cancel: "إلغاء ",
    httpRequestError: "حدث خطأ في الطلب.",
    y_axie: "زاوية إمالة",
    id_haixiu: "خجول",
    rhinoceros: "وحيد القرن",
    id_servo: "محرِّك",
    monkey: "قرد",
    id_control_repeat_times: "مرات",
    sound_effects_recording_delete: "حذف",
    reflectance: "انعكاس",
    angle: "زاوية",
    id_zhayan: "وميض العين",
    id_wink: "غمز",
    course_hide: "إخفاء",
    listVariable: "قائمة",
    id_yun: "مصاب بدوار",
    horse: "حصان",
    emotion_engine: "محرك",
    project_pop_ok_btn: "موافق",
    variable_inputrule_msg: "لا يمكن أن تبدأ رقما. يتعذر إدخال الأحرف الخاصة. يمكن إدخال %1 من الأحرف أو %2 من الأحرف الصينية كحد أقصى.",
    id_infinite_loop_error: "الذاكرة تكاد تكون مشغولة، أعد المحاولة بعد العودة",
    catFunctions: "الوظائف",
    show_count: "عرض المؤقِّت",
    let_show_countdown: "عرض العدّ التنازلي مع أنبوب nixie",
    id_sensor_touch_sensor: "مستشعر اللمس",
    catVariables: "المتغيرات",
    id_happy: "سعيد",
    gyro_rotate_direction_popup_ok: "موافق",
    posture_ok_desc: "الوضع بعد إدخال اسم الوضع",
    title_setting_emotion: "الرمز التعبيري للإعداد",
    id_sensor_angle: "زاوية",
    tilt_left: "إمالة لليسار",
    no_common_servo_info: "لا يوجد معزِّز وضع الزاوية حاليًا (يمكن التدوير ضمن نطاق معين). هل تحتاج إلى إعداد واحد؟",
    id_sensor_touch_sensor_status: "الحالة",
    id_events: "الأحداث",
    exit_tips: "لم يتم حفظ البرنامج الحالي، هل تريد الاستمرار أم الخروج؟",
    db_click: "النقر المزدوج",
    delay: "تأخير",
    touch_tone: "نغمة اللمس",
    lose: "ضائع",
    pig: "خنزير",
    id_stop_info: "إيقاف",
    step_1: "خطوة 1",
    servo_angle: "زاوية",
    disconnected: "قطع الاتصال",
    servo_angle_popup_variable: "المتغير",
    sysVoiceName: "الصوت",
    servo_status_popup_adjustable: "فتح قفل",
    id_start_info: "تشغيل",
    movement_gesture: "الإجراء",
    id_shangxin: "حزين",
    porject_alert_content_05: "عذرًا، كتلة البرنامج في ملف المشروع تحتوي على أخطاء!",
    speed_VF: "سرعة بالغة",
    servo_id: "ID",
    add_project_input_check: "يمكن إدخال 16 حرفًا فقط",
    speed_S: "بطيئة",
    catColour: "اللون",
    emotion: "المشاعر",
    press_hold: "الضغط مع الثبات",
    id_sensor_angle_to_zero: "كل الزاوايا على صفر",
    recording_name_repeat: "تكرار الاسم المسجَّل",
    ringtones: "نغمات الرنين",
    runTooltip: "قم بتشغيل البرنامج المحدد بالكتل في مساحة العمل.",
    servo_mode_error: "خطأ في وضع المُعزِّز",
    linkTooltip: "الحفظ والربط بالكتل.",
    id_go_to_start: "انتقل إلى بدء",
    ambulance: "سيارة إسعاف",
    tilt_down: "إمالة لأسفل",
    yes: "نعم فعلا",
    step_5: "خطوة 5",
    step_6: "خطوة 6",
    step_7: "خطوة 7",
    step_8: "خطوة 8",
    step_9: "خطوة 9",
    step_10: "خطوة 10",
    step_11: "خطوة 11",
    step_12: "خطوة 12",
    step_13: "خطوة 13",
    step_14: "خطوة 14",
    step_15: "خطوة 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"أغنية 1",
    flexin:"أغنية 2"
    /* 逻辑编程新增歌曲翻译 end*/
};