var MSG = {
    id_all_bright: "all bright",
    show_countdown: "Show countdown",
    porject_alert_content: "Sorry, wrong parameter for operating target. Please check!",
    sound_effects_popup_ok: "OK",
    servo_speed: "speed",
    gyro_rotate_direction_popup_house: "Pitch angle",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Block introduction",
    servo_angle_popup_close: "Close",
    id_show_show_emoji: "Show emoji",
    exit_popup_title: "Tips",
    london_bridge: "Song 3",
    step_2: "Step 2",
    id_degree: "degree",
    busy_tone: "Busy tone",
    servo_angle_popup_title: "Set rotation angle for servo motor",
    rotate_servo_popup_anti_clockwise: "Anti-clockwise",
    long_lighton: "Always on",
    posture_set_desc: "Open the right switch and set action of robot",
    recording_alert_ok: "OK",
    porject_alert_content_02: "Error in base service operation. The error message",
    block_error_info: "Current block exist error, please check it and try again.",
    sound_effects_popup_cancel: "Cancel",
    id_close_eyes: "close eyes",
    carhorn1: "Carhorn1",
    id_fengshan: "Fan",
    project_has_no_change: "The current program has not changed",
    id_sensor_set_gyroscope: "Set gyroscope",
    servo_angle_popup_angle: "Angle",
    id_show_play_effect: "Play effect",
    sound_effects_recording_add: "Add new recording",
    recording_tips: "Recording",
    id_control_break: "Out of circulation",
    no_circle_servo_info: "There is currently no wheel mode servo (can rotate 360°). Do you need to set one up?",
    recording: "Recording",
    run_msg: "Let Jimu move as you have programmed it!",
    id_control: "Control",
    variable_named_too_long: "variable name could not exceed %1 characters",
    movements: "movements",
    let_show_count: "Show timer with nixie tube",
    id_servos: "Rotate servos",
    recording_data_tips: "No records",
    title_infrared_sensor: "Infrared Sensor Setting",
    add_project_pop_title: "Project name",
    step_3: "Step 3",
    id_rotate: "rotate",
    trashTooltip: "Discard all blocks.",
    id_smile: "smile",
    id_show_time_during: "for",
    task: "Missio",
    title_variable_set: "Set Variable",
    id_control_wait_for: "Wait until",
    z_axie: "Heading angle",
    cheerful: "Cheerful",
    id_to: "to",
    machine: "Machine",
    title_setting_tune: "Setting Tune",
    surprise: "Surprise",
    badCode: "Program err",
    dog: "Dog",
    no_project_tip: "No project, click + on the upper right corner to create one!",
    id_daze: "daze",
    id_sensor_IR_sensor: "IR sensor",
    recording_ok: "OK",
    infrared_tips: "Infrared sensor is not connected to the current model",
    swift_msg: "Tap here to view the swift code!",
    id_unlock: "unlock",
    see_example: "View sample",
    recording_name_popup_msg: "Recording name contains invalid characters",
    tiger: "Tiger",
    variable_named_popup_placeholder: "Variable",
    id_set: "Set",
    recording_popup_title: "Recorded file name input",
    police_car_1: "Police_car_1",
    title_setting_light: "Setting Light",
    servo_status_popup_tips: "You cannot adjust the corresponding servo for the robot when in locked mode",
    help_desc: "Tap here to view helpful tips when you have a problem!",
    let_led_scenelight: "Show scene lighting with LED lights",
    step_4: "Step 4",
    posture_named_popup_cancel: "Cancel",
    id_rotate_circle: "Rotate servo 360°",
    id_show: "Show",
    speed_VS: "very slow",
    porject_alert_content_06: "Project saved",
    porject_alert_tips: "Tips",
    id_in: "during",
    telephone_call: "Telephone Call",
    recording_alert_title: "Error",
    ir_sensor: "IR Sensor",
    id_sensor_reflectance_between_obstacle: "reflectance between obstacle",
    btn_name_confirm: "ok",
    id_start: "Start",
    id_show_scenelight: "Show Light Display",
    add_project_placeholder: "Project name",
    id_when_start: "Click 'Run' to start",
    yawn: "Yawn",
    id_repeat: "Repeat",
    servo_status_popup_ok: "OK",
    sealions: "Sealions",
    gyro_rotate_direction_popup_cancel: "Cancel",
    blocks: "Blocks",
    release: "Release",
    posture_link_popup_title: "The model connect",
    giraffe: "Giraffe",
    recording_named_too_long: "variable name could not exceed %1 characters",
    title_setting_scenelight: "Set Up Light Display",
    touch_sensor: "Touch sensor",
    catLists: "Lists",
    id_actions: "Moves",
    id_custom: "custom",
    support: "Support",
    servo_status_popup_title: "Set status of servo motor",
    gyro_rotate_direction_popup_course: "Heading angle",
    hashError: "Sorry, '%1' doesn't correspond with any saved program.",
    recording_alert_content: "privilege grant failed",
    id_huxi: "Breath",
    shumaguan: "Digital Tube",
    cow: "Cow",
    textVariable: "text",
    porject_alert_content_03: "Error in data received from base!",
    doorbell: "Doorbell",
    posture_named_popup_ok: "OK",
    axie: "axie",
    show_number: "Show number",
    let_show_time: "Show time with nixie tube",
    move: "Move",
    touch_tips: "The touch sensor is not connected to the current model",
    gyroscope_tips: "The gyro sensor is not connected to the current model",
    id_run_to: "Run to",
    project_pop_cancel_btn: "Cancel",
    tilt_up: "Tilt up",
    show_time: "Show time",
    posture_link_popup_cancel: "cancel",
    speed: "speed",
    robot: "Robot",
    id_cry: "cry",
    exit_popup_ok: "OK",
    id_jingya: "Surprised",
    id_shanshuo: "Flash",
    set_servo_mode: "Set Servo Mode",
    tilt_swing: "Tilt swing",
    posture_link: "The model is not connected. Please connect the model first",
    id_control_wait: "Wait",
    bear: "Bear",
    select_all: "All",
    servo_direction: "direction",
    projectlist_msg: "View the programs Jimu has learned and mastered and create new programs for it!",
    input_rule_msg: "Cannot begin with a digit. A maximum of %1 characters or %2 Chinese characters can be entered.",
    lights_tips: "The current model is not connected to any light",
    posture_link_popup_ok: "ok",
    posture_named_popup_title: "Name the action",
    laser: "Laser",
    newProjectName: "NewProject",
    title_device_tilt: "Phone/Tablet status setting",
    variable_named_popup_msg: "variable name contains illegal characters",
    x_axie: "Roll angle",
    recording_title: "Recording",
    chicken: "Chicken",
    title_bluetooth_connect: "Bluetooth Connect",
    video_desc: "Tap here to have a look at task description videos!",
    phone_pad: "Phone/Tablet",
    carhorn: "Carhorn",
    id_control_repeat: "Repeat",
    servo_angle_popup_cancel: "Cancel",
    id_show_play_tune: "Play tune",
    let_stop_count: "Stop timer with nixie tube",
    gyro_rotate_direction_popup_horizontal: "Roll angle",
    angry: "Angry",
    id_millsecond: "ms",
    badXml: "Error parsing X",
    gyro_rotate_direction_popup_curVal: "Current value",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Action",
    project_name_popup_msg: "Project name contains invalid characters",
    porject_alert_btnText: "OK",
    id_disco: "Disco",
    id_caise: "Color Stacking",
    title: "Code",
    fail: "Failure",
    btn_name_cancel: "cancel",
    yankee_doodle: "Song 4",
    snoring: "Snoring",
    id_math_not: "Not",
    doubt: "Doubt",
    nonsense: "Raving",
    bird: "Bird",
    speed_F: "fast",
    save_project_msg: "Tap here to save your program!",
    actingcute: "Cute",
    speed_no_value: "Current equipment wheelless steering",
    recording_placeholder: "Please enter a recording name",
    servo_status_popup_locking: "Lock",
    walrus: "Walrus",
    help_msg: "Tap here if you have any questions!",
    is_add_project_pop_tips: "Save current project?",
    servo_angle_popup_ok: "OK",
    catText: "Text",
    servo_status_popup_cancel: "Cancel",
    linkAlert: "Share your blocks with this li",
    id_sanyuanse: "Primary Colors",
    porject_alert_title: "Error",
    id_yugua: "Wipers",
    id_math: "Math",
    id_relei: "Tears",
    received: "Receive",
    add_recording_ok: "OK",
    current_value: "current value",
    engine: "Engine",
    id_deng: "7Colored Lights",
    porject_alert_content_04: "Failed to read project",
    gyroscope: "Gyroscope",
    transfiguration: "Transform",
    id_sad: "sad",
    project_name_too_long: "Project name could not exceed %1 characters",
    id_all: "All",
    posture_named_popup_msg: "Action name contains illegal characters",
    title_touch_sensor: "Touch sensor setting",
    id_moves: "Moves",
    id_fadai: "Dazed",
    posture_named_too_long: "Action name could not exceed %1 characters",
    sound_effects_popup_title: "Set sound effects",
    rotate_servo_popup_title: "Rotating Mode",
    command: "Command",
    id_show_show_LEDs: "Show LEDs",
    id_sensors: "Sensors",
    let_show_number: "Show number with nixie tube",
    cover: "Shield",
    go_skip: "Skip",
    id_show_times: "times",
    course_tips: "Cannot be viewed now!",
    maincontrol_box: "Maincontrol box",
    id_while: "While",
    xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
    police_car_2: "Police_car_2",
    is_add_project_pop_title: "Save project",
    tilt_right: "Tilt right",
    set_countdown: "Countdown setting",
    rotate_servo_popup_stop: "stop",
    id_until: "Until",
    index_back: "Back",
    id_blue_disconnect: "Bluetooth is not connected",
    touch_tips_error: "The current block ID is not correct, please delete it and reset",
    catLogic: "Logic",
    id_sensor_gyroscope: "Gyroscope",
    animal: "Animal",
    status: "status is",
    catMath: "Math",
    recording_cancel: "Canncel",
    speed_M: "middle",
    speed_only_360_value: "Current equipment has no angle mode servo",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Select rotation direction for servo motor",
    happy: "Happy",
    catLoops: "Loops",
    id_open_eyes: "open eyes",
    servo: "Servo",
    course_show: "View",
    id_ok: "OK",
    title_time_adjust: "Time Adjust",
    porject_alert_content_01: "Item name already exists. Please enter again.",
    meebot: "Meebot",
    timeout: "Maximum execution iterations exceeded.",
    project_list_title: "My Projects",
    rotate_servo_popup_clockwise: "Clockwise",
    close_blue: "Bluetooth is connected, it does disconnect?",
    wave: "Wave",
    lion: "Lion",
    click: "Click",
    id_leiguang: "Flashing Tears",
    id_lock: "lock",
    elephant: "Elephant",
    exit_popup_cancel: "Cancel",
    complete: "Complete",
    stop_count: "Stop timer",
    low_power: "Low power",
    id_dizzy: "dizzy",
    rotate_servo_popup_ok: "OK",
    rotate_servo_popup_cancel: "Cancel",
    httpRequestError: "There was a problem with the request.",
    y_axie: "Pitch angle",
    id_haixiu: "Shy",
    rhinoceros: "Rhinoceros",
    id_servo: "Servo",
    monkey: "Monkey",
    id_control_repeat_times: "times",
    sound_effects_recording_delete: "Delete",
    reflectance: "reflectance",
    angle: "angle",
    id_zhayan: "Blink",
    id_wink: "wink",
    course_hide: "Hide",
    listVariable: "list",
    id_yun: "Dizzy",
    horse: "Horse",
    emotion_engine: "Engine",
    project_pop_ok_btn: "OK",
    variable_inputrule_msg: "Cannot begin with a digit. Special characters cannot be entered. A maximum of %1 characters or %2 Chinese characters can be entered.",
    id_infinite_loop_error: "Program exit due to out of memory, please return back and retry",
    catFunctions: "Functions",
    show_count: "Show timer",
    let_show_countdown: "Show countdown with nixie tube",
    id_sensor_touch_sensor: "Touch sensor",
    catVariables: "Variables",
    id_happy: "Happy",
    gyro_rotate_direction_popup_ok: "OK",
    posture_ok_desc: "Pose after input position name",
    title_setting_emotion: "Setting Emotion",
    id_sensor_angle: "angle",
    tilt_left: "Tilt left",
    no_common_servo_info: "There is currently no angle mode servo (can rotate within a designated range). Do you need to set one up?",
    id_sensor_touch_sensor_status: "status",
    id_events: "Events",
    exit_tips: "The current program is not saved, whether to continue to exit？",
    db_click: "Double Click",
    delay: "delay",
    touch_tone: "Touch Tone",
    lose: "Lost",
    pig: "Pig",
    id_stop_info: "Stop",
    step_1: "Step 1",
    servo_angle: "Angle",
    disconnected: "Disconnected",
    servo_angle_popup_variable: "Variable",
    sysVoiceName: "voice",
    servo_status_popup_adjustable: "Unlock",
    id_start_info: "Run",
    movement_gesture: "Action",
    id_shangxin: "Sad",
    porject_alert_content_05: "Sorry, the program block in the project file contains errors!",
    speed_VF: "very fast",
    servo_id: "ID",
    add_project_input_check: "Can only enter 16 characters",
    speed_S: "slow",
    catColour: "Colour",
    emotion: "Emotion",
    press_hold: "Press Hold",
    id_sensor_angle_to_zero: "all angle to zero degrees",
    recording_name_repeat: "Recorded Name Repeat",
    ringtones: "Ringtones",
    runTooltip: "Run the program defined by the blocks in the workspace.",
    servo_mode_error: "servo mode error",
    linkTooltip: "Save and link to blocks.",
    id_go_to_start: "Go to start",
    ambulance: "Ambulance",
    tilt_down: "Tilt down",
    yes: "Yes",
    step_5: "Step 5",
    step_6: "Step 6",
    step_7: "Step 7",
    step_8: "Step 8",
    step_9: "Step 9",
    step_10: "Step 10",
    step_11: "Step 11",
    step_12: "Step 12",
    step_13: "Step 13",
    step_14: "Step 14",
    step_15: "Step 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Song 1",
    flexin:"Song 2"
    /* 逻辑编程新增歌曲翻译 end*/
};