var MSG = {
    id_all_bright: "todo brillante",
    show_countdown: "Mostrar cta. atrás",
    porject_alert_content: "El parámetro de la meta operativa es incorrecto. Verifíquelo.",
    sound_effects_popup_ok: "Aceptar",
    servo_speed: "velocidad",
    gyro_rotate_direction_popup_house: "Ángulo de paso",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Introducción de bloque",
    servo_angle_popup_close: "Cerrar",
    id_show_show_emoji: "Mostrar emoji",
    exit_popup_title: "Consejos",
    london_bridge: "Canción 3",
    step_2: "Paso 2",
    id_degree: "grado",
    busy_tone: "Tono ocupado",
    servo_angle_popup_title: "Establecer ángulo de rotación para servomotor",
    rotate_servo_popup_anti_clockwise: "En sentido contrahorario",
    long_lighton: "Encendido",
    posture_set_desc: "Abre el conmutador y define la acción del robot.",
    recording_alert_ok: "Aceptar",
    porject_alert_content_02: "Se ha producido un error en la operación de servicio base. El mensaje de error",
    block_error_info: "Hay un error en el bloque actual. Compruébalo y vuelve a intentarlo.",
    sound_effects_popup_cancel: "Cancelar ",
    id_close_eyes: "cerrar ojos",
    carhorn1: "Altavoz de vehículo 1",
    id_fengshan: "Ventilador",
    project_has_no_change: "El programa actual no ha sido modificado.",
    id_sensor_set_gyroscope: "Establecer giroscopio",
    servo_angle_popup_angle: "Ángulo",
    id_show_play_effect: "Reproducir efecto",
    sound_effects_recording_add: "Agregar nueva grabación",
    recording_tips: "Grabando",
    id_control_break: "Fuera de bucle",
    no_circle_servo_info: "Actualmente, no hay ningún servomotor de modo de rueda (capacidad de giro de 360°). ¿Quieres configurar uno?",
    recording: "grabación",
    run_msg: "Deja que Jimu realice las acciones que has programado para él!",
    id_control: "Control",
    variable_named_too_long: "El nombre del proyecto no debe superar los %1 caracteres.",
    movements: "movimientos",
    let_show_count: "Mostrar temporiz. con tubo Nixie",
    id_servos: "Girar servomotores",
    recording_data_tips: "No hay grabaciones.",
    title_infrared_sensor: "Configuración de sensor infrarrojo",
    add_project_pop_title: "Nombre de proyecto",
    step_3: "Paso 3",
    id_rotate: "girar",
    trashTooltip: "Descartar todos los bloques.",
    id_smile: "sonreír",
    id_show_time_during: "durante",
    task: "Misión",
    title_variable_set: "Establecer variable",
    id_control_wait_for: "Esperar hasta",
    z_axie: "Ángulo de encabezado",
    cheerful: "Alegre",
    id_to: "a",
    machine: "máquina",
    title_setting_tune: "Estableciendo tono",
    surprise: "Sorpresa",
    badCode: "Error de programa",
    dog: "perro",
    no_project_tip: "No hay proyectos. Haz clic en + en la esquina superior derecha para crear uno.",
    id_daze: "Aturdido",
    id_sensor_IR_sensor: "Sensor infrarrojo",
    recording_ok: "Aceptar",
    infrared_tips: "El modelo en uso no está conectado a ningún sensor infrarrojo",
    swift_msg: "Toca aquí para ver el código swift!",
    id_unlock: "desbloquear",
    see_example: "Ver muestra",
    recording_name_popup_msg: "El nombre de la grabación contiene caracteres no válidos.",
    tiger: "tigre",
    variable_named_popup_placeholder: "Variable",
    id_set: "Establecer",
    recording_popup_title: "Entrada de nombre del archivo grabado",
    police_car_1: "Coche de policía 1",
    title_setting_light: "Estableciendo iluminación",
    servo_status_popup_tips: "No puede ajustar el servomotor correspondiente para el robot en el modo bloqueado.",
    help_desc: "Toca aquí para ver consejos útiles si tienes algún problema.",
    let_led_scenelight: "Mostrar iluminación de escena con luces LED",
    step_4: "Paso 4",
    posture_named_popup_cancel: "Cancelar ",
    id_rotate_circle: "Girar servomotor 360°",
    id_show: "Reprod.",
    speed_VS: "muy lento",
    porject_alert_content_06: "Proyecto guardado",
    porject_alert_tips: "Consejos",
    id_in: "durante",
    telephone_call: "Llamada telefónica",
    recording_alert_title: "Error",
    ir_sensor: "Sensor infrarrojo",
    id_sensor_reflectance_between_obstacle: "reflectancia entre obstáculo",
    btn_name_confirm: "aceptar",
    id_start: "Iniciar",
    id_show_scenelight: "Mostrar indicador LED",
    add_project_placeholder: "Nombre de proyecto",
    id_when_start: "Pulse \"Ejecutar\" para comenzar",
    yawn: "Bostezo",
    id_repeat: "Repetir",
    servo_status_popup_ok: "Aceptar",
    sealions: "león marino",
    gyro_rotate_direction_popup_cancel: "Cancelar ",
    blocks: "Bloques",
    release: "Soltar",
    posture_link_popup_title: "Conexión del modelo",
    giraffe: "jirafa",
    recording_named_too_long: "El nombre del proyecto no debe superar los %1 caracteres.",
    title_setting_scenelight: "Configurar indicador LED",
    touch_sensor: "Sensor táctil",
    catLists: "Listas",
    id_actions: "Mov.",
    id_custom: "personalizar",
    support: "Apoyo",
    servo_status_popup_title: "Establecer estado del servomotor",
    gyro_rotate_direction_popup_course: "Ángulo de encabezado",
    hashError: "'%1' no corresponde con ningún programa guardado.",
    recording_alert_content: "Error al conceder el privilegio",
    id_huxi: "Respiración",
    shumaguan: "Tubo Nixie",
    cow: "vaca",
    textVariable: "texto",
    porject_alert_content_03: "Se ha producido un error en los datos recibidos de la base.",
    doorbell: "Timbre",
    posture_named_popup_ok: "Aceptar",
    axie: "eje",
    show_number: "Mostrar número",
    let_show_time: "Mostrar tiempo con tubo Nixie",
    move: "Movimiento",
    touch_tips: "El modelo en uso no está conectado a ningún sensor táctil",
    gyroscope_tips: "El modelo en uso no está conectado a ningún sensor giroscopio",
    id_run_to: "Ejecutar a",
    project_pop_cancel_btn: "Cancelar ",
    tilt_up: "Inclinar hacia arriba",
    show_time: "Mostrar tiempo",
    posture_link_popup_cancel: "cancelar",
    speed: "velocidad",
    robot: "robot",
    id_cry: "llorar",
    exit_popup_ok: "Aceptar",
    id_jingya: "Sorprendido",
    id_shanshuo: "Parpadeo",
    set_servo_mode: "Configuración",
    tilt_swing: "Inclinar para balancear",
    posture_link: "El modelo no está conectado. Primero conéctelo.",
    id_control_wait: "Esperar",
    bear: "oso",
    select_all: "Todo",
    servo_direction: "dirección",
    projectlist_msg: "Mira los programas que Jimu ha aprendido y dominado, y crea nuevos programas para él!",
    input_rule_msg: "No se puede comenzar con un dígito. Se puede introducir un máximo de %1 caracteres o %2 caracteres chinos.",
    lights_tips: "El modelo actual no está conectado a la luz.",
    posture_link_popup_ok: "aceptar",
    posture_named_popup_title: "Pon nombre a la acción.",
    laser: "Láser",
    newProjectName: "Nuevo proyecto",
    title_device_tilt: "Config. de estado de teléfono/tableta",
    variable_named_popup_msg: "El nombre de la variable contiene caracteres no permitidos.",
    x_axie: "Ángulo de rotación",
    recording_title: "Grabando",
    chicken: "pollo",
    title_bluetooth_connect: "Conexión Bluetooth",
    video_desc: "Toca aquí para ver los vídeos de descripción de tareas.",
    phone_pad: "Teléfono/tableta",
    carhorn: "Altavoz de vehículo",
    id_control_repeat: "Repetir",
    servo_angle_popup_cancel: "Cancelar ",
    id_show_play_tune: "Reproducir tono",
    let_stop_count: "Detener temporiz. con tubo Nixie",
    gyro_rotate_direction_popup_horizontal: "Ángulo de rotación",
    angry: "Enojado",
    id_millsecond: "ms",
    badXml: "Error al analizar XML.",
    gyro_rotate_direction_popup_curVal: "Valor actual",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Acción",
    project_name_popup_msg: "El nombre del proyecto contiene caracteres inválidos.",
    porject_alert_btnText: "Aceptar",
    id_disco: "Disco",
    id_caise: "Superposición de luces",
    title: "Código",
    fail: "Fracaso",
    btn_name_cancel: "cancelar",
    yankee_doodle: "Canción 4",
    snoring: "Ronquidos",
    id_math_not: "No",
    doubt: "Pregunta",
    nonsense: "Delirante",
    bird: "pájaro",
    speed_F: "rápido",
    save_project_msg: "Toca aquí para guardar tu programa!",
    actingcute: "Linda",
    speed_no_value: "El servomotor del modelo actual no tiene un modo de rotación de 360º.",
    recording_placeholder: "Introduzca un nombre para la grabación.",
    servo_status_popup_locking: "Bloquear",
    walrus: "morsa",
    help_msg: "Toca aquí si tienes alguna pregunta!",
    is_add_project_pop_tips: "¿Desea guardar el proyecto actual?",
    servo_angle_popup_ok: "Aceptar",
    catText: "Texto",
    servo_status_popup_cancel: "Cancelar ",
    linkAlert: "Comparte los bloques con este enlace",
    id_sanyuanse: "Colores primarios",
    porject_alert_title: "Error",
    id_yugua: "Limpiaparabrisas",
    id_math: "Math",
    id_relei: "Lágrimas",
    received: "Recibir",
    add_recording_ok: "Aceptar",
    current_value: "valor actual",
    engine: "Motor",
    id_deng: "Indicador LED de 7 colores",
    porject_alert_content_04: "No se ha podido leer el proyecto.",
    gyroscope: "Giroscopio",
    transfiguration: "Transformar",
    id_sad: "Triste",
    project_name_too_long: "El nombre del proyecto no debe superar los %1 caracteres.",
    id_all: "Todo",
    posture_named_popup_msg: "El nombre de la acción contiene caracteres no permitidos.",
    title_touch_sensor: "Configuración de sensor táctil",
    id_moves: "Mov.",
    id_fadai: "Aturdido",
    posture_named_too_long: "El nombre de la acción no debe superar los %1 caracteres.",
    sound_effects_popup_title: "Establecer efectos de sonido",
    rotate_servo_popup_title: "Modo de rotación",
    command: "Mando",
    id_show_show_LEDs: "Activar LED",
    id_sensors: "Sensores",
    let_show_number: "Mostrar número con tubo Nixie",
    cover: "Proteger",
    go_skip: "Omitir",
    id_show_times: "veces",
    course_tips: "Ahora no se puede ver.",
    maincontrol_box: "Caja de control principal",
    id_while: "Mientras",
    xmlError: "No se ha podido cargar el archivo guardado. Es posible que se haya creado con otra versión de Blockly?",
    police_car_2: "Coche de policía 2",
    is_add_project_pop_title: "Guardar proyecto",
    tilt_right: "Inclinar a dcha.",
    set_countdown: "Ajustes cuenta atrás",
    rotate_servo_popup_stop: "Detener",
    id_until: "Hasta",
    index_back: "Atrás",
    id_blue_disconnect: "Bluetooth desconectada",
    touch_tips_error: "El ID actual del bloque no es correcto, elimínelo y restablezca",
    catLogic: "Lógica",
    id_sensor_gyroscope: "Giroscopio",
    animal: "animal",
    status: "el estado es",
    catMath: "Math",
    recording_cancel: "Cancelar ",
    speed_M: "medio",
    speed_only_360_value: "El equipamiento actual no tiene servomotor de modo de ángulo.",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Selecciona la dirección de rotación del servomotor.",
    happy: "Contento",
    catLoops: "Bucles",
    id_open_eyes: "ojos abiertos",
    servo: "Servomotor",
    course_show: "Ver",
    id_ok: "Aceptar",
    title_time_adjust: "Ajuste de hora",
    porject_alert_content_01: "El nombre del artículo ya existe. Introduzca un nombre de nuevo.",
    meebot: "meebot",
    timeout: "Se ha superado el límite de iteraciones de ejecución.",
    project_list_title: "Mis proyectos",
    rotate_servo_popup_clockwise: "En sentido horario",
    close_blue: "Conexión Bluetooth activa. ¿Deseas desactivarla?",
    wave: "Saludar",
    lion: "león",
    click: "Clic",
    id_leiguang: "Lágrimas luminosas",
    id_lock: "bloquear",
    elephant: "elefante",
    exit_popup_cancel: "Cancelar ",
    complete: "Completar",
    stop_count: "Detener temporiz.",
    low_power: "Batería baja",
    id_dizzy: "Mareado",
    rotate_servo_popup_ok: "Aceptar",
    rotate_servo_popup_cancel: "Cancelar ",
    httpRequestError: "Se ha producido un problema con la solicitud.",
    y_axie: "Ángulo de paso",
    id_haixiu: "Tímido",
    rhinoceros: "rinoceronte",
    id_servo: "Servomotor",
    monkey: "mono",
    id_control_repeat_times: "veces",
    sound_effects_recording_delete: "Eliminar",
    reflectance: "reflectancia",
    angle: "ángulo",
    id_zhayan: "Guiño",
    id_wink: "Guiño",
    course_hide: "Ocultar",
    listVariable: "lista",
    id_yun: "Mareado",
    horse: "caballo",
    emotion_engine: "Motor",
    project_pop_ok_btn: "Aceptar",
    variable_inputrule_msg: "No se puede comenzar con un dígito. No se pueden introducir caracteres especiales. Se puede introducir un máximo de %1 caracteres o %2 caracteres chinos.",
    id_infinite_loop_error: "La memoria está casi llena, intente de nuevo tras volver",
    catFunctions: "Funciones",
    show_count: "Mostrar temporiz.",
    let_show_countdown: "Mostrar cta. atrás con tubo Nixie",
    id_sensor_touch_sensor: "Sensor táctil",
    catVariables: "Variables",
    id_happy: "Contento",
    gyro_rotate_direction_popup_ok: "Aceptar",
    posture_ok_desc: "Define la postura del robot para crear una acción y ponerle nombre.",
    title_setting_emotion: "Estableciendo emoción",
    id_sensor_angle: "ángulo",
    tilt_left: "Inclinar a izqda.",
    no_common_servo_info: "Actualmente, no hay ningún servomotor de modo de ángulo (capacidad de giro de en un ángulo especificado). ¿Quieres configurar uno?",
    id_sensor_touch_sensor_status: "estado",
    id_events: "Eventos",
    exit_tips: "El programa actual no está guardado. ¿Deseas continuar para salir?",
    db_click: "Doble clic",
    delay: "Detraso",
    touch_tone: "Marcación por tonos",
    lose: "Perdido",
    pig: "cerdo",
    id_stop_info: "Detener",
    step_1: "Paso 1",
    servo_angle: "Ángulo",
    disconnected: "Desconectado",
    servo_angle_popup_variable: "Variable",
    sysVoiceName: "voz",
    servo_status_popup_adjustable: "Desbloquear",
    id_start_info: "Ejecutar",
    movement_gesture: "Acción",
    id_shangxin: "Triste",
    porject_alert_content_05: "El bloque del programa en el archivo del proyecto contiene errores.",
    speed_VF: "muy rápido",
    servo_id: "ID",
    add_project_input_check: "Solo se pueden introducir 16 caracteres.",
    speed_S: "lento",
    catColour: "Color",
    emotion: "Emoción",
    press_hold: "Mantener",
    id_sensor_angle_to_zero: "todos los ángulos a cero grados",
    recording_name_repeat: "Repetición de nombre grabado",
    ringtones: "tonos",
    runTooltip: "Ejecutar el programa definido por los bloques en el espacio de trabajo.",
    servo_mode_error: "Error de modo de servomotor",
    linkTooltip: "Guardar y enlazar a bloques.",
    id_go_to_start: "Ve al inicio.",
    ambulance: "Ambulancia",
    tilt_down: "Inclinar hacia abajo",
    yes: "Sí",
    step_5: "Paso 5",
    step_6: "Paso 6",
    step_7: "Paso 7",
    step_8: "Paso 8",
    step_9: "Paso 9",
    step_10: "Paso 10",
    step_11: "Paso 11",
    step_12: "Paso 12",
    step_13: "Paso 13",
    step_14: "Paso 14",
    step_15: "Paso 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Canción 1",
    flexin:"Canción 2"
    /* 逻辑编程新增歌曲翻译 end*/
};