var MSG = {
    id_all_bright: "Complètement illuminé",
    show_countdown: "Afficher le compte à rebours",
    porject_alert_content: "Désolé, les paramètres définis ne peuvent réaliser l'opération souhaitée. Veuillez vérifier !",
    sound_effects_popup_ok: "OK",
    servo_speed: "vitesse",
    gyro_rotate_direction_popup_house: "Angle d'attaque",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Présentation du bloc",
    servo_angle_popup_close: "Fermer",
    id_show_show_emoji: "Afficher les émojis",
    exit_popup_title: "Conseils",
    london_bridge: "Chanson 3",
    step_2: "Étape 2",
    id_degree: "degré",
    busy_tone: "Signal occupé",
    servo_angle_popup_title: "Définir l'angle de rotation pour le moteur du servo",
    rotate_servo_popup_anti_clockwise: "Sens antihoraire",
    long_lighton: "Toujours allumé",
    posture_set_desc: "Basculer le commutateur de droite et définir l'action du robot",
    recording_alert_ok: "OK",
    porject_alert_content_02: "Les opérations du service de base contiennent une erreur. Le message d'erreur",
    block_error_info: "Le bloc sélectionné a rencontré une erreur, veuillez vérifier et essayer à nouveau.",
    sound_effects_popup_cancel: "Annuler ",
    id_close_eyes: "fermer les yeux",
    carhorn1: "Enceinte 1 du véhicule",
    id_fengshan: "Ventilateur",
    project_has_no_change: "Le programme en cours ne peut être modifié",
    id_sensor_set_gyroscope: "Définir le gyroscope",
    servo_angle_popup_angle: "Angle",
    id_show_play_effect: "Lecture d'effet",
    sound_effects_recording_add: "Ajouter un nouvel enregistrement",
    recording_tips: "Enregistrement",
    id_control_break: "Boucle interrompue",
    no_circle_servo_info: "Aucun servo en mode Roue (rotation possible sur 360°). Voulez-vous en configurer un ?",
    recording: "enregistrement",
    run_msg: "Laissez Jimu se déplacer comme vous l'avez programmé !",
    id_control: "Contrôle",
    variable_named_too_long: "Le nom d'utilisateur est limité %1 caractères",
    movements: "déplacements",
    let_show_count: "Afficher le chronomètre sur les tubes Nixie",
    id_servos: "Pivoter le servo",
    recording_data_tips: "Aucun enregistrement",
    title_infrared_sensor: "Paramètres du capteur infrarouge",
    add_project_pop_title: "Nom du projet",
    step_3: "Étape 3",
    id_rotate: "pivoter",
    trashTooltip: "Annuler tous les blocs.",
    id_smile: "sourire",
    id_show_time_during: "pour",
    task: "Mission",
    title_variable_set: "Définir la variable",
    id_control_wait_for: "Attendre jusqu'à",
    z_axie: "Angle de cap",
    cheerful: "Joyeux",
    id_to: "à",
    machine: "machine",
    title_setting_tune: "Paramètres audio",
    surprise: "Surprise",
    badCode: "Erreur de programme",
    dog: "chien",
    no_project_tip: "Aucun projet, veuillez cliquer sur + dans le coin supérieur droit pour en créer un !",
    id_daze: "Stupéfaction",
    id_sensor_IR_sensor: "Capteur infrarouge",
    recording_ok: "OK",
    infrared_tips: "Le modèle actuel n'est pas connecté à un capteur infrarouge.",
    swift_msg: "Appuyez ici pour voir le code Swift !",
    id_unlock: "déverrouiller",
    see_example: "Afficher l'exemple",
    recording_name_popup_msg: "Le nom enregistré contient des caractères non valides",
    tiger: "tigre",
    variable_named_popup_placeholder: "Variable",
    id_set: "Définir",
    recording_popup_title: "Saisie du nom de fichier enregistré",
    police_car_1: "Voiture de police 1",
    title_setting_light: "Paramètres de l'éclairage",
    servo_status_popup_tips: "Le servo correspondant du robot ne peut être paramétré en mode verrouillé",
    help_desc: "Appuyez ici pour consulter des astuces lorsque vous rencontrez un problème !",
    let_led_scenelight: "Éclairer l'avant avec les lampes LED",
    step_4: "Étape 4",
    posture_named_popup_cancel: "Annuler ",
    id_rotate_circle: "Pivoter le servo à 360°",
    id_show: "Afficher",
    speed_VS: "très lentement",
    porject_alert_content_06: "Projet enregistré",
    porject_alert_tips: "Conseils",
    id_in: "pendant",
    telephone_call: "Appel téléphonique",
    recording_alert_title: "Erreur",
    ir_sensor: "Capteur infrarouge",
    id_sensor_reflectance_between_obstacle: "réflexion entre obstacle",
    btn_name_confirm: "OK",
    id_start: "Begin",
    id_show_scenelight: "Affichage du voyant LED",
    add_project_placeholder: "Nom du projet",
    id_when_start: "Appuyez sur « Exécuter » pour démarrer",
    yawn: "Bâillement",
    id_repeat: "Répéter",
    servo_status_popup_ok: "OK",
    sealions: "otaries",
    gyro_rotate_direction_popup_cancel: "Annuler ",
    blocks: "Blocs",
    release: "Relâcher",
    posture_link_popup_title: "Connexion du modèle",
    giraffe: "girafe",
    recording_named_too_long: "Le nom d'utilisateur est limité %1 caractères",
    title_setting_scenelight: "Configuration du voyant LED",
    touch_sensor: "Capteur tactile",
    catLists: "Listes",
    id_actions: "Activités",
    id_custom: "personnalisé",
    support: "Soutien",
    servo_status_popup_title: "Définir l'état pour le moteur du servo",
    gyro_rotate_direction_popup_course: "Angle de cap",
    hashError: "Désolé, « %1 » ne correspond à aucun programme enregistré.",
    recording_alert_content: "l'autorisation de l'enregistrement a échoué",
    id_huxi: "Respiration",
    shumaguan: "Tube Nixie",
    cow: "vache",
    textVariable: "texte",
    porject_alert_content_03: "Les données reçues depuis la base contiennent une erreur !",
    doorbell: "Sonnette de porte",
    posture_named_popup_ok: "OK",
    axie: "axe",
    show_number: "Afficher un nombre",
    let_show_time: "Afficher l'heure sur les tubes Nixie",
    move: "Bouge toi",
    touch_tips: "Le modèle actuel n'est pas connecté à un capteur tactile.",
    gyroscope_tips: "Le modèle actuel n'est pas connecté à un capteur gyroscopique.",
    id_run_to: "Exécuter",
    project_pop_cancel_btn: "Annuler ",
    tilt_up: "Incliner vers le haut",
    show_time: "Afficher l'heure",
    posture_link_popup_cancel: "annuler",
    speed: "vitesse",
    robot: "robot",
    id_cry: "pleurer",
    exit_popup_ok: "OK",
    id_jingya: "Surprise",
    id_shanshuo: "Scintillement",
    set_servo_mode: "Paramètres",
    tilt_swing: "Balancer",
    posture_link: "Le modèle n'est pas connecté. Veuillez d'abord connecter le modèle",
    id_control_wait: "Attendre",
    bear: "ours",
    select_all: "Tout",
    servo_direction: "direction",
    projectlist_msg: "Découvrez les programmes appris et maîtrisés par Jimu et créez-en lui de nouveaux !",
    input_rule_msg: "Impossible de commencer par un chiffre. Un maximum de %1 caractères ou %2 caractères chinois peut être saisi.",
    lights_tips: "Le modèle en cours n'est connecté à aucune lumière",
    posture_link_popup_ok: "OK",
    posture_named_popup_title: "Nommer la posture",
    laser: "Laser",
    newProjectName: "Nouveau projet",
    title_device_tilt: "Paramètres d'état du téléphone/ de la tablette",
    variable_named_popup_msg: "le nom de variable contient des caractères non valides",
    x_axie: "Angle de roulis",
    recording_title: "Enregistrement",
    chicken: "poulet",
    title_bluetooth_connect: "Connexion Bluetooth",
    video_desc: "Appuyez ici pour découvrir des vidéos sur des descriptions de tâches !",
    phone_pad: "Téléphone/ tablette",
    carhorn: "Enceinte du véhicule",
    id_control_repeat: "Répéter",
    servo_angle_popup_cancel: "Annuler ",
    id_show_play_tune: "Lecture audio",
    let_stop_count: "Arrêter l'affichage du chronomètre sur les tubes Nixie",
    gyro_rotate_direction_popup_horizontal: "Angle de roulis",
    angry: "En colère",
    id_millsecond: "ms",
    badXml: "Erreur d'analyse XML",
    gyro_rotate_direction_popup_curVal: "Valeur actuelle",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Action",
    project_name_popup_msg: "Le nom de projet contient des caractères non valides",
    porject_alert_btnText: "OK",
    id_disco: "Disco",
    id_caise: "Superposition des couleurs",
    title: "Code",
    fail: "Échec",
    btn_name_cancel: "annuler",
    yankee_doodle: "Chanson 4",
    snoring: "Ronflement",
    id_math_not: "Non",
    doubt: "Question",
    nonsense: "Délirant",
    bird: "oiseau",
    speed_F: "rapide",
    save_project_msg: "Appuyez ici pour enregistrer votre programme !",
    actingcute: "Mignonne",
    speed_no_value: "Le servo du modèle en cours n'est pas en mode rotation à 360° ",
    recording_placeholder: "Veuillez saisir un nom d'enregistrement",
    servo_status_popup_locking: "Verrouiller",
    walrus: "morse",
    help_msg: "Appuyez ici si vous avez des questions !",
    is_add_project_pop_tips: "Enregistrer le projet en cours ?",
    servo_angle_popup_ok: "OK",
    catText: "Texte",
    servo_status_popup_cancel: "Annuler ",
    linkAlert: "Partagez vos blocs à l'aide de ce lien",
    id_sanyuanse: "Couleurs primaires",
    porject_alert_title: "Erreur",
    id_yugua: "Essuie-glace",
    id_math: "Math",
    id_relei: "Pleurs",
    received: "Recevoir",
    add_recording_ok: "OK",
    current_value: "valeur actuelle",
    engine: "Moteur",
    id_deng: "Arc-en-ciel",
    porject_alert_content_04: "Lecture du projet impossible",
    gyroscope: "Gyroscope",
    transfiguration: "Transformer",
    id_sad: "Tristesse",
    project_name_too_long: "Le nom d'utilisateur est limité %1 caractères",
    id_all: "Tout",
    posture_named_popup_msg: "Le nom de l'action contient des caractères non valides",
    title_touch_sensor: "Paramètres du capteur tactile",
    id_moves: "Activités",
    id_fadai: "Stupéfaction",
    posture_named_too_long: "Le nom de l'action est limité à %1 caractères",
    sound_effects_popup_title: "Définir les effets sonores",
    rotate_servo_popup_title: "Mode de rotation",
    command: "Commander",
    id_show_show_LEDs: "Afficher les voyants",
    id_sensors: "Capteurs",
    let_show_number: "Afficher le nombre sur le tube Nixie",
    cover: "Bouclier",
    go_skip: "Sauter",
    id_show_times: "fois",
    course_tips: "Affichage impossible !",
    maincontrol_box: "Boîtier de commande principal",
    id_while: "Pendant que",
    xmlError: "Votre fichier enregistré n'a pu être chargé. Il a peut-être été créé avec une version différente de Blockly.",
    police_car_2: "Voiture de police 2",
    is_add_project_pop_title: "Enregistrer le projet",
    tilt_right: "Incliner à droite",
    set_countdown: "Paramètres du compte à rebours",
    rotate_servo_popup_stop: "s'arrêter",
    id_until: "Jusqu'à",
    index_back: "Arrière",
    id_blue_disconnect: "La connexion Bluetooth n'est pas établie",
    touch_tips_error: "L'ID du bloc actuel n'est pas correct, veuillez le supprimer et le réinitialiser",
    catLogic: "Logique",
    id_sensor_gyroscope: "Gyroscope",
    animal: "animal",
    status: "l'état est",
    catMath: "Math",
    recording_cancel: "Annuler ",
    speed_M: "au centre",
    speed_only_360_value: "Le modèle en cours ne dispose d'aucun servo en mode angulaire",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Sélectionner le sens de rotation pour le moteur du servo",
    happy: "Content",
    catLoops: "Boucles",
    id_open_eyes: "yeux ouverts",
    servo: "Servo",
    course_show: "Afficher",
    id_ok: "OK",
    title_time_adjust: "Ajustement de la durée",
    porject_alert_content_01: "Le nom de l'article existe déjà. Veuillez saisir un autre nom.",
    meebot: "meeBot",
    timeout: "Le nombre maximal de répétitions d'exécution a été dépassé.",
    project_list_title: "Mes projets",
    rotate_servo_popup_clockwise: "Sens horaire",
    close_blue: "La fonctionnalité Bluetooth est activée, le modèle se déconnecte-t-il ?",
    wave: "Saluer",
    lion: "lion",
    click: "Appuyer",
    id_leiguang: "Larmes clignotantes",
    id_lock: "verrouiller",
    elephant: "éléphant",
    exit_popup_cancel: "Annuler ",
    complete: "Achevée",
    stop_count: "Arrêter le chronomètre",
    low_power: "Basse puissance",
    id_dizzy: "Étourdissement",
    rotate_servo_popup_ok: "OK",
    rotate_servo_popup_cancel: "Annuler ",
    httpRequestError: "La demande a rencontré un problème.",
    y_axie: "Angle d'attaque",
    id_haixiu: "Timidité",
    rhinoceros: "rhinocéros",
    id_servo: "Servo",
    monkey: "singe",
    id_control_repeat_times: "fois",
    sound_effects_recording_delete: "Supprimer",
    reflectance: "réflectivité",
    angle: "angle",
    id_zhayan: "Clin d'œil",
    id_wink: "Clin d'œil",
    course_hide: "Masquer",
    listVariable: "liste",
    id_yun: "Étourdissement",
    horse: "cheval",
    emotion_engine: "Moteur",
    project_pop_ok_btn: "OK",
    variable_inputrule_msg: "Impossible de commencer par un chiffre. Les caractères spéciaux ne sont pas pris en charge. Un maximum de %1 caractères ou %2 caractères chinois peut être saisi.",
    id_infinite_loop_error: "La mémoire est presque pleine, réessayez en revenant.",
    catFunctions: "Fonctions",
    show_count: "Afficher le chronomètre",
    let_show_countdown: "Afficher le compte à rebours sur les tubes Nixie",
    id_sensor_touch_sensor: "Capteur tactile",
    catVariables: "Variables",
    id_happy: "Joie",
    gyro_rotate_direction_popup_ok: "OK",
    posture_ok_desc: "Pose après le nom de position d'entrée",
    title_setting_emotion: "Paramètres des émoticônes",
    id_sensor_angle: "angle",
    tilt_left: "Incliner à gauche",
    no_common_servo_info: "Aucun servo en mode Angle (rotation possible selon la plage désignée). Voulez-vous en configurer un ?",
    id_sensor_touch_sensor_status: "état",
    id_events: "Event",
    exit_tips: "Le programme en cours ne peut être enregistré, souhaitez-vous néanmoins quitter ?",
    db_click: "Appuyer deux fois",
    delay: "Retard",
    touch_tone: "Clavier",
    lose: "Perdu",
    pig: "cochon",
    id_stop_info: "S'arrêter",
    step_1: "Étape 1",
    servo_angle: "Angle",
    disconnected: "Déconnecté",
    servo_angle_popup_variable: "Variable",
    sysVoiceName: "voix",
    servo_status_popup_adjustable: "Déverrouiller",
    id_start_info: "Exécuter",
    movement_gesture: "Action",
    id_shangxin: "Tristesse",
    porject_alert_content_05: "Désolé, le bloc du programme dans le fichier du projet contient des erreurs !",
    speed_VF: "très rapide",
    servo_id: "ID",
    add_project_input_check: "Un maximum de 16 caractères peut être saisi",
    speed_S: "lentement",
    catColour: "Couleur",
    emotion: "Émotion",
    press_hold: "Appuyer et maintenir",
    id_sensor_angle_to_zero: "tous les angles à 0°",
    recording_name_repeat: "Le nom enregistré existe déjà",
    ringtones: "sonneries",
    runTooltip: "Exécutez le programme défini par les blocs dans l'espace de travail.",
    servo_mode_error: "Erreur de mode de servo",
    linkTooltip: "Enregistrez et joignez aux blocs.",
    id_go_to_start: "Aller sur Démarrer",
    ambulance: "Ambulance",
    tilt_down: "Incliner vers le bas",
    yes: "Oui",
    step_5: "Étape 5",
    step_6: "Étape 6",
    step_7: "Étape 7",
    step_8: "Étape 8",
    step_9: "Étape 9",
    step_10: "Étape 10",
    step_11: "Étape 11",
    step_12: "Étape 12",
    step_13: "Étape 13",
    step_14: "Étape 14",
    step_15: "Étape 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Chanson 1",
    flexin:"Chanson 2"
    /* 逻辑编程新增歌曲翻译 end*/
};