var MSG = {
    id_all_bright: "tutto luminoso",
    show_countdown: "Mostra countdown",
    porject_alert_content: "Parametro errato per il target operativo. Verifica.",
    sound_effects_popup_ok: "OK",
    servo_speed: "velocità",
    gyro_rotate_direction_popup_house: "Angolo di inclinazione",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Blocca introduzione",
    servo_angle_popup_close: "Chiudi",
    id_show_show_emoji: "Visualizza emoji",
    exit_popup_title: "Suggerimenti",
    london_bridge: "Brano 3",
    step_2: "Fase 2",
    id_degree: "grado",
    busy_tone: "Tono occupato",
    servo_angle_popup_title: "Imposta angolo di rotazione per il servomotore",
    rotate_servo_popup_anti_clockwise: "Senso antiorario",
    long_lighton: "Sempre ON",
    posture_set_desc: "Apri interruttore destro e imposta l'azione del robot",
    recording_alert_ok: "OK",
    porject_alert_content_02: "Errore nel funzionamento del servizio di base. Mess. errore",
    block_error_info: "Problema con il blocco esistente. Riprovare.",
    sound_effects_popup_cancel: "Cancella ",
    id_close_eyes: "occhi chiusi",
    carhorn1: "Altoparlante veicolo 1",
    id_fengshan: "Ventilatore",
    project_has_no_change: "Il programma corrente non ha subito modifiche",
    id_sensor_set_gyroscope: "Imposta giroscopio",
    servo_angle_popup_angle: "Angolo",
    id_show_play_effect: "Riproduci effetto",
    sound_effects_recording_add: "Aggiungi nuova registrazione",
    recording_tips: "Registrazione",
    id_control_break: "Ciclo interrotto",
    no_circle_servo_info: "Nessuna modalità ruota del servomotore attualmente disponibile (è possibile effettuare una rotazione di 360°). Configurarne una?",
    recording: "registrazione",
    run_msg: "Fai muovere Jimu in base alla tua programmazione!",
    id_control: "Controllo",
    variable_named_too_long: "Il nome del progetto non può superare i %1 caratteri",
    movements: "movimenti",
    let_show_count: "Mostra timer con tubo nixie",
    id_servos: "Ruota servo",
    recording_data_tips: "0 registr.",
    title_infrared_sensor: "Impostazione sensore a infrarossi",
    add_project_pop_title: "Nome progetto",
    step_3: "Fase 3",
    id_rotate: "ruota",
    trashTooltip: "Rimuovi tutti i blocchi.",
    id_smile: "sorridente",
    id_show_time_during: "per",
    task: "Missione",
    title_variable_set: "Imposta variabile",
    id_control_wait_for: "Attendi fino",
    z_axie: "Angolo girodirezionale",
    cheerful: "gioioso",
    id_to: "a",
    machine: "macchina",
    title_setting_tune: "Impostazione melodia",
    surprise: "Sorpresa",
    badCode: "Errore programma",
    dog: "cane",
    no_project_tip: "Nessun progetto, fai clic su + in alto a destra per crearne uno.",
    id_daze: "Sbalordito",
    id_sensor_IR_sensor: "Sensore IR",
    recording_ok: "OK",
    infrared_tips: "Il modello corrente non è collegato a un sensore a infrarossi",
    swift_msg: "Tocca qui per visualizzare il codice SWIFT!",
    id_unlock: "sblocca",
    see_example: "Visualizza es.",
    recording_name_popup_msg: "Nome registrazione contiene caratteri non validi",
    tiger: "tigre",
    variable_named_popup_placeholder: "Variabile",
    id_set: "Imposta",
    recording_popup_title: "Input nome file registrato",
    police_car_1: "Auto della polizia 1",
    title_setting_light: "Impostazione indicatore",
    servo_status_popup_tips: "Impossibile regolare il servomotore corrispondente per il robot quando in modalità bloccata",
    help_desc: "Toccare qui per visualizzare consigli utili in caso di problemi",
    let_led_scenelight: "Mostra luci di scena con spie LED",
    step_4: "Fase 4",
    posture_named_popup_cancel: "Cancella ",
    id_rotate_circle: "Ruota il servomotore di 360°",
    id_show: "Mostra",
    speed_VS: "molto lento",
    porject_alert_content_06: "Progetto salvato",
    porject_alert_tips: "Suggerimenti",
    id_in: "durante",
    telephone_call: "Chiamata",
    recording_alert_title: "Errore",
    ir_sensor: "Sensore IR",
    id_sensor_reflectance_between_obstacle: "riflessione tra ostacolo",
    btn_name_confirm: "ok",
    id_start: "Avvia",
    id_show_scenelight: "Visualizza indicatore LED",
    add_project_placeholder: "Nome progetto",
    id_when_start: "Fai clic su \"Esegui\" per iniziare",
    yawn: "Sbadiglio",
    id_repeat: "Ripeti",
    servo_status_popup_ok: "OK",
    sealions: "leoni marini",
    gyro_rotate_direction_popup_cancel: "Cancella ",
    blocks: "Blocchi",
    release: "Rilascia",
    posture_link_popup_title: "Connessione modello",
    giraffe: "giraffa",
    recording_named_too_long: "Il nome del progetto non può superare i %1 caratteri",
    title_setting_scenelight: "Configura indicatore LED",
    touch_sensor: "Sensore a sfioramento",
    catLists: "Elenchi",
    id_actions: "Mosse",
    id_custom: "personalizza",
    support: "Supporto",
    servo_status_popup_title: "Imposta stato del servomotore",
    gyro_rotate_direction_popup_course: "Angolo girodirezionale",
    hashError: "\" % 1\" non corrisponde ad alcun programma salvato.",
    recording_alert_content: "concessione privilegiata non riuscita",
    id_huxi: "Respiro",
    shumaguan: "Tubo nixie",
    cow: "mucca",
    textVariable: "testo",
    porject_alert_content_03: "Errore nei dati ricevuti dalla base.",
    doorbell: "Campanello",
    posture_named_popup_ok: "OK",
    axie: "asse",
    show_number: "Mostra numero",
    let_show_time: "Mostra ora con tubo nixie",
    move: "Mossa",
    touch_tips: "Il modello corrente non è collegato a un sensore a sfioramento",
    gyroscope_tips: "Il modello corrente non è collegato a un sensore giroscopico",
    id_run_to: "Esegui",
    project_pop_cancel_btn: "Cancella ",
    tilt_up: "Inclina verso l'alto",
    show_time: "Mostra ora",
    posture_link_popup_cancel: "cancella",
    speed: "velocità",
    robot: "robot",
    id_cry: "che piange",
    exit_popup_ok: "OK",
    id_jingya: "Sorpreso",
    id_shanshuo: "Scintilla",
    set_servo_mode: "Impostazioni",
    tilt_swing: "Inclina per oscillare",
    posture_link: "Il modello non è connesso. Connettere prima il modello",
    id_control_wait: "Attendi",
    bear: "orso",
    select_all: "Tutto",
    servo_direction: "direzione",
    projectlist_msg: "Visualizza i programmi che Jimu ha imparato e in cui è ormai un esperto e crea nuovi programmi per lui!",
    input_rule_msg: "Non può iniziare con una cifra. È possibile inserire un massimo di %1 caratteri o %2 caratteri cinesi.",
    lights_tips: "Modello corrente non connesso ad alcun indicatore",
    posture_link_popup_ok: "ok",
    posture_named_popup_title: "Denomina l'azione",
    laser: "Laser",
    newProjectName: "Nuovo progetto",
    title_device_tilt: "Impost. stato telefono/tablet",
    variable_named_popup_msg: "il nome della variabile contiene caratteri non validi",
    x_axie: "Angolo di rollio",
    recording_title: "Registrazione",
    chicken: "gallina",
    title_bluetooth_connect: "Connessione Bluetooth",
    video_desc: "Toccare qui per i video di descrizione attività",
    phone_pad: "Telefono/Tablet",
    carhorn: "Altoparlante veicolo",
    id_control_repeat: "Ripeti",
    servo_angle_popup_cancel: "Cancella ",
    id_show_play_tune: "Riproduci melodia",
    let_stop_count: "Ferma timer con tubo nixie",
    gyro_rotate_direction_popup_horizontal: "Angolo di rollio",
    angry: "Arrabbiato",
    id_millsecond: "ms",
    badXml: "Errore analisi XML",
    gyro_rotate_direction_popup_curVal: "Valore corrente",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Azione",
    project_name_popup_msg: "Il nome del progetto contiene caratteri non validi",
    porject_alert_btnText: "OK",
    id_disco: "Disco",
    id_caise: "Impilamento colori",
    title: "Codice",
    fail: "Fallimento",
    btn_name_cancel: "annulla",
    yankee_doodle: "Brano 4",
    snoring: "russare",
    id_math_not: "Non",
    doubt: "Domanda",
    nonsense: "delirante",
    bird: "uccello",
    speed_F: "veloce",
    save_project_msg: "Tocca qui per salvare il tuo programma!",
    actingcute: "Carina",
    speed_no_value: "Servo del modello corrente privo di rotazione 360°",
    recording_placeholder: "Inserisci un nome di registrazione",
    servo_status_popup_locking: "Blocca",
    walrus: "tricheco",
    help_msg: "Tocca qui se hai ulteriori domande!",
    is_add_project_pop_tips: "Salvare il progetto corrente?",
    servo_angle_popup_ok: "OK",
    catText: "Testo",
    servo_status_popup_cancel: "Cancella ",
    linkAlert: "Condividi blocchi con questo link",
    id_sanyuanse: "Colori primari",
    porject_alert_title: "Errore",
    id_yugua: "Tergicristalli",
    id_math: "Mate",
    id_relei: "Lacrime",
    received: "Ricevere",
    add_recording_ok: "OK",
    current_value: "valore corrente",
    engine: "Motore",
    id_deng: "7 indicatori colorati",
    porject_alert_content_04: "Impossibile leggere il progetto",
    gyroscope: "Giroscopio",
    transfiguration: "Trasformare",
    id_sad: "Triste",
    project_name_too_long: "Il nome del progetto non può superare i %1 caratteri",
    id_all: "Tutto",
    posture_named_popup_msg: "Nome dell'azione contiene caratteri non validi",
    title_touch_sensor: "Impostazione sensore a sfioramento",
    id_moves: "Mosse",
    id_fadai: "Sbalordito",
    posture_named_too_long: "Il nome dell'azione non può superare i %1 caratteri",
    sound_effects_popup_title: "Imposta effetti audio",
    rotate_servo_popup_title: "Modalità di rotazione",
    command: "Comando",
    id_show_show_LEDs: "Visualizza LED",
    id_sensors: "Sensori",
    let_show_number: "Mostra numero con tubo nixie",
    cover: "Scudo",
    go_skip: "Ignora",
    id_show_times: "volte",
    course_tips: "Impossibile visualizzare.",
    maincontrol_box: "Scatola di comando principale",
    id_while: "Durante",
    xmlError: "Impossibile caricare il file salvato. È possibile che sia stato creato con una diversa versione di Blockly?",
    police_car_2: "Auto della polizia 2",
    is_add_project_pop_title: "Salva progetto",
    tilt_right: "Inclina a destra",
    set_countdown: "Impostaz. countdown",
    rotate_servo_popup_stop: "Arresta",
    id_until: "Fino a",
    index_back: "Indietro",
    id_blue_disconnect: "Bluetooth non connesso",
    touch_tips_error: "La corrente ID blocco non è corretto, si prega di eliminarlo e ripristinare",
    catLogic: "Logica",
    id_sensor_gyroscope: "Giroscopio",
    animal: "animale",
    status: "lo stato è",
    catMath: "Matematica",
    recording_cancel: "Cancella ",
    speed_M: "intermedio",
    speed_only_360_value: "Modello corrente non dispone di servo con mod. angolare",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Seleziona la direzione di rotazione per il servomotore",
    happy: "Contento",
    catLoops: "Cicli",
    id_open_eyes: "Apri gli occhi",
    servo: "Servomotore",
    course_show: "Visualizza",
    id_ok: "OK",
    title_time_adjust: "Regolazione ora",
    porject_alert_content_01: "Nome elemento già esistente. Inseriscilo di nuovo.",
    meebot: "meebot",
    timeout: "Numero massimo di iterazioni superato.",
    project_list_title: "I miei progetti",
    rotate_servo_popup_clockwise: "Senso orario",
    close_blue: "Il Bluetooth è connesso. Si disconnette?",
    wave: "Saluta",
    lion: "leone",
    click: "Fai clic",
    id_leiguang: "Lacrime luminose",
    id_lock: "blocca",
    elephant: "elefante",
    exit_popup_cancel: "Cancella ",
    complete: "Completare",
    stop_count: "Ferma timer",
    low_power: "Basso consumo",
    id_dizzy: "Frastornato",
    rotate_servo_popup_ok: "OK",
    rotate_servo_popup_cancel: "Cancella ",
    httpRequestError: "Si è verificato un problema con la richiesta.",
    y_axie: "Angolo di inclinazione",
    id_haixiu: "Timido",
    rhinoceros: "rinoceronte",
    id_servo: "Servomotore",
    monkey: "scimmia",
    id_control_repeat_times: "volte",
    sound_effects_recording_delete: "Elimina",
    reflectance: "riflettività",
    angle: "angolo",
    id_zhayan: "Occhiolino",
    id_wink: "Occhiolino",
    course_hide: "Nascondi",
    listVariable: "elenco",
    id_yun: "Frastornato",
    horse: "cavallo",
    emotion_engine: "Motore",
    project_pop_ok_btn: "OK",
    variable_inputrule_msg: "Non può iniziare con una cifra. Impossibile inserire caratteri speciali. È possibile inserire un massimo di %1 caratteri o %2 caratteri cinesi.",
    id_infinite_loop_error: "La memoria è quasi piena. Riprova dopo il ritorno",
    catFunctions: "Funzioni",
    show_count: "Mostra timer",
    let_show_countdown: "Mostra countdown con tubo nixie",
    id_sensor_touch_sensor: "Sensore a sfioramento",
    catVariables: "Variabili",
    id_happy: "Felice",
    gyro_rotate_direction_popup_ok: "OK",
    posture_ok_desc: "Imp. posiz. robot per azione e nominala",
    title_setting_emotion: "Impostazione emozione",
    id_sensor_angle: "angolo",
    tilt_left: "Inclina a sinistra",
    no_common_servo_info: "Nessuna modalità di angolazione del servomotore attualmente disponibile (è possibile effettuare una rotazione entro un intervallo designato). Configurarne una?",
    id_sensor_touch_sensor_status: "stato",
    id_events: "Eventi",
    exit_tips: "Il programma corrente non è stato salvato. Uscire?",
    db_click: "Fai doppio clic",
    delay: "Ritardo",
    touch_tone: "Composizione a toni",
    lose: "Perduto",
    pig: "maiale",
    id_stop_info: "Arresta",
    step_1: "Fase 1",
    servo_angle: "Angolo",
    disconnected: "Scollegato",
    servo_angle_popup_variable: "Variabile",
    sysVoiceName: "voce",
    servo_status_popup_adjustable: "Sblocca",
    id_start_info: "Esegui",
    movement_gesture: "Azione",
    id_shangxin: "Triste",
    porject_alert_content_05: "Il blocco programma nel file del progetto contiene errori.",
    speed_VF: "molto veloce",
    servo_id: "ID",
    add_project_input_check: "Può contenere solo 16 caratteri",
    speed_S: "lento",
    catColour: "Colore",
    emotion: "Emozione",
    press_hold: "Premi Sospendi",
    id_sensor_angle_to_zero: "Tutti gli angoli a 0°",
    recording_name_repeat: "Nome registrato ripetuto",
    ringtones: "suonerie",
    runTooltip: "Esegui il programma definito dai blocchi nell'area di lavoro.",
    servo_mode_error: "Errore modalità servomotore",
    linkTooltip: "Salva e collega a blocchi.",
    id_go_to_start: "Vai all'inizio",
    ambulance: "Ambulanza",
    tilt_down: "Inclina verso il basso",
    yes: "sì",
    step_5: "Fase 5",
    step_6: "Fase 6",
    step_7: "Fase 7",
    step_8: "Fase 8",
    step_9: "Fase 9",
    step_10: "Fase 10",
    step_11: "Fase 11",
    step_12: "Fase 12",
    step_13: "Fase 13",
    step_14: "Fase 14",
    step_15: "Fase 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Brano 1",
    flexin:"Brano 2"
    /* 逻辑编程新增歌曲翻译 end*/
};