var MSG = {
    id_all_bright: "모두 밝음",
    show_countdown: "카운트다운 표시",
    porject_alert_content: "죄송합니다, 작동 대상에 잘못된 파라미터입니다. 확인해주십시오!",
    sound_effects_popup_ok: "확인",
    servo_speed: "속도",
    gyro_rotate_direction_popup_house: "피치 각도",
    id_math_variables_set_add: "%1 + %2",
    help_title: "블록 소개",
    servo_angle_popup_close: "닫기",
    id_show_show_emoji: "이모티콘 표시",
    exit_popup_title: "도움말",
    london_bridge: "노래 3",
    step_2: "단계 2",
    id_degree: "도",
    busy_tone: "통화 중 톤",
    servo_angle_popup_title: "서보 모터 회전 각도 설정",
    rotate_servo_popup_anti_clockwise: "반시계 방향",
    long_lighton: "항상 켜짐",
    posture_set_desc: "오른쪽 스위치를 열고 로봇 동작을 설정합니다.",
    recording_alert_ok: "확인",
    porject_alert_content_02: "베이스 서비스 작업 오류 오류 메시지",
    block_error_info: "현재 블록 존재 오류. 확인 후 다시 시도하십시오.",
    sound_effects_popup_cancel: "취소 ",
    id_close_eyes: "눈 감기",
    carhorn1: "차량 스피커 1",
    id_fengshan: "팬",
    project_has_no_change: "현재 프로그램이 변경되지 않았습니다.",
    id_sensor_set_gyroscope: "자이로스코프 설정",
    servo_angle_popup_angle: "각도",
    id_show_play_effect: "플레이 효과",
    sound_effects_recording_add: "새 기록 추가",
    recording_tips: "기록",
    id_control_break: "루프 종료",
    no_circle_servo_info: "현재 바퀴 모드 서보(360° 회전 가능)가 없습니다. 설정하시겠습니까?",
    recording: "기록",
    run_msg: "Jimu를 프로그램한 대로 움직이게 합니다!",
    id_control: "제어",
    variable_named_too_long: "프로젝트 이름은 %1 글자를 초과할 수 없습니다.",
    movements: "동작",
    let_show_count: "Nixie 튜브로 타이머 표시",
    id_servos: "서보 회전",
    recording_data_tips: "기록 없음",
    title_infrared_sensor: "적외선 센서 설정",
    add_project_pop_title: "프로젝트 이름",
    step_3: "단계 3",
    id_rotate: "회전",
    trashTooltip: "모든 블록 폐기",
    id_smile: "미소",
    id_show_time_during: "동안",
    task: "미시오",
    title_variable_set: "변수 설정",
    id_control_wait_for: "다음 때까지 대기",
    z_axie: "헤딩 각도",
    cheerful: "즐거운",
    id_to: "대상",
    machine: "기계",
    title_setting_tune: "튠 설정",
    surprise: "놀람",
    badCode: "프로그램 오류",
    dog: "개",
    no_project_tip: "프로젝트가 없습니다. 프로젝트를 생성하려면 오른쪽 상단 코너에서 +를 클릭하십시오.",
    id_daze: "현혹",
    id_sensor_IR_sensor: "IR 센서",
    recording_ok: "확인",
    infrared_tips: "현재 모델이 적외선 센서에 연결되어 있지 않습니다.",
    swift_msg: "스위프트 코드를 확인하려면 여기를 탭하십시오!",
    id_unlock: "잠금 해제",
    see_example: "샘플 보기",
    recording_name_popup_msg: "기록 이름에 잘못된 문자가 포함되어 있습니다.",
    tiger: "호랑이",
    variable_named_popup_placeholder: "변수",
    id_set: "설정",
    recording_popup_title: "기록된 파일 이름 입력",
    police_car_1: "경찰차 1",
    title_setting_light: "조명 설정",
    servo_status_popup_tips: "잠금 모드에서는 로봇의 해당 서보를 조정할 수 없습니다.",
    help_desc: "문제가 발생했을 때 유용한 팁을 보려면 여기를 클릭하십시오!",
    let_led_scenelight: "LED 빛으로 장면 라이트닝 표시",
    step_4: "단계 4",
    posture_named_popup_cancel: "취소 ",
    id_rotate_circle: "서보 360° 회전",
    id_show: "표시",
    speed_VS: "매우 느림",
    porject_alert_content_06: "프로젝트 저장됨",
    porject_alert_tips: "도움말",
    id_in: "동안",
    telephone_call: "전화",
    recording_alert_title: "오류",
    ir_sensor: "IR 센서",
    id_sensor_reflectance_between_obstacle: "장애물_간_반사율",
    btn_name_confirm: "확인",
    id_start: "시작",
    id_show_scenelight: "조명 디스플레이 보기",
    add_project_placeholder: "프로젝트 이름",
    id_when_start: "‘실행’을 클릭하여 시작",
    yawn: "하품 소리",
    id_repeat: "반복",
    servo_status_popup_ok: "확인",
    sealions: "바다사자",
    gyro_rotate_direction_popup_cancel: "취소 ",
    blocks: "블록",
    release: "해제",
    posture_link_popup_title: "모델 연결",
    giraffe: "기린",
    recording_named_too_long: "프로젝트 이름은 %1 글자를 초과할 수 없습니다.",
    title_setting_scenelight: "조명 디스플레이 설정",
    touch_sensor: "터치 센서",
    catLists: "목록",
    id_actions: "이동",
    id_custom: "사용자 지정",
    support: "지원하다",
    servo_status_popup_title: "서보 모터 상태 설정",
    gyro_rotate_direction_popup_course: "헤딩 각도",
    hashError: "죄송합니다. ‘%1’에 해당하는 저장된 프로그램이 없습니다.",
    recording_alert_content: "권한 부여 실패",
    id_huxi: "입김",
    shumaguan: "Nixie 튜브",
    cow: "소",
    textVariable: "텍스트",
    porject_alert_content_03: "베이스에서 수신한 데이터 오류!",
    doorbell: "초인종",
    posture_named_popup_ok: "확인",
    axie: "액슬",
    show_number: "숫자 표시",
    let_show_time: "Nixie 튜브로 시간 표시",
    move: "움직임",
    touch_tips: "현재 모델이 터치 센서에 연결되어 있지 않습니다.",
    gyroscope_tips: "현재 모델이 자이로스코프 센서에 연결되어 있지 않습니다.",
    id_run_to: "실행",
    project_pop_cancel_btn: "취소 ",
    tilt_up: "위로 기울이기",
    show_time: "시간 표시",
    posture_link_popup_cancel: "취소",
    speed: "속도",
    robot: "로봇",
    id_cry: "울음",
    exit_popup_ok: "확인",
    id_jingya: "놀람",
    id_shanshuo: "반짝임",
    set_servo_mode: "설정",
    tilt_swing: "기울여 돌리기",
    posture_link: "모델이 연결되지 않았습니다. 모델을 먼저 연결하십시오.",
    id_control_wait: "대기",
    bear: "곰",
    select_all: "전체",
    servo_direction: "방향",
    projectlist_msg: "Jimu가 학습하고 마스터한 프로그램을 보고 Jimu를 위한 새 프로그램을 생성합니다!",
    input_rule_msg: "숫자로 시작할 수 없습니다. 최대 %1 문자 또는 %2 중국어 문자를 입력할 수 있습니다.",
    lights_tips: "현재 모델이 어떤 라이트하고도 연결되어 있지 않습니다.",
    posture_link_popup_ok: "확인",
    posture_named_popup_title: "작동 이름 지정",
    laser: "레이저",
    newProjectName: "새 프로젝트",
    title_device_tilt: "폰/태블릿 상태 설정",
    variable_named_popup_msg: "변수 이름에 규칙에 어긋난 글자가 포함되어 있습니다.",
    x_axie: "롤 각도",
    recording_title: "기록",
    chicken: "닭",
    title_bluetooth_connect: "Bluetooth 연결",
    video_desc: "작업 설명 비디오를 보려면 여기를 클릭하십시오!",
    phone_pad: "폰/태블릿",
    carhorn: "차량 스피커",
    id_control_repeat: "반복",
    servo_angle_popup_cancel: "취소 ",
    id_show_play_tune: "플레이 튠",
    let_stop_count: "Nixie 튜브로 타이머 중지",
    gyro_rotate_direction_popup_horizontal: "롤 각도",
    angry: "성난",
    id_millsecond: "ms",
    badXml: "XML 분석 중 오류",
    gyro_rotate_direction_popup_curVal: "현재 값",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "작동",
    project_name_popup_msg: "프로젝트 이름에 유효하지 않은 글자가 포함되어 있습니다.",
    porject_alert_btnText: "확인",
    id_disco: "Disco",
    id_caise: "컬러 스태킹",
    title: "코드",
    fail: "실패",
    btn_name_cancel: "취소",
    yankee_doodle: "노래 4",
    snoring: "쿨쿨",
    id_math_not: "not",
    doubt: "문제",
    nonsense: "미쳐 날뛰는",
    bird: "새",
    speed_F: "빠름",
    save_project_msg: "프로그램을 저장하려면 여기를 탭하십시오!",
    actingcute: "귀엽다",
    speed_no_value: "현재 모델의 서보는 360도 회전 모드가 제공되지 않습니다.",
    recording_placeholder: "기록 이름을 입력하십시오",
    servo_status_popup_locking: "잠금",
    walrus: "바다코끼리",
    help_msg: "질문이 있다면 여기를 탭하십시오!",
    is_add_project_pop_tips: "현재 프로젝트를 저장하시겠습니까?",
    servo_angle_popup_ok: "확인",
    catText: "텍스트",
    servo_status_popup_cancel: "취소 ",
    linkAlert: "블록을 이 링크와 공유",
    id_sanyuanse: "기본 색상",
    porject_alert_title: "오류",
    id_yugua: "와이퍼",
    id_math: "수학",
    id_relei: "눈물",
    received: "받다",
    add_recording_ok: "확인",
    current_value: "현재 값",
    engine: "엔진",
    id_deng: "7색 조명",
    porject_alert_content_04: "프로젝트 읽기 실패",
    gyroscope: "자이로스코프",
    transfiguration: "변환",
    id_sad: "슬픔",
    project_name_too_long: "프로젝트 이름은 %1 글자를 초과할 수 없습니다.",
    id_all: "전체",
    posture_named_popup_msg: "작동 이름에 잘못된 문자가 포함되어 있습니다.",
    title_touch_sensor: "터치 센서 설정",
    id_moves: "이동",
    id_fadai: "현혹",
    posture_named_too_long: "작업 이름은 %1자를 초과할 수 없습니다.",
    sound_effects_popup_title: "음향 효과 설정",
    rotate_servo_popup_title: "회전 모드",
    command: "명령",
    id_show_show_LEDs: "LED 표시",
    id_sensors: "센서",
    let_show_number: "Nixie 튜브로 숫자 표시",
    cover: "방패",
    go_skip: "건너뛰기",
    id_show_times: "회",
    course_tips: "지금은 볼 수 없습니다!",
    maincontrol_box: "메인컨트롤 박스",
    id_while: "동안",
    xmlError: "저장된 파일을 로드하지 못했습니다. 다른 버전의 Blockly로 만들어졌습니까?",
    police_car_2: "경찰차 2",
    is_add_project_pop_title: "프로젝트 저장",
    tilt_right: "오른쪽 기울이기",
    set_countdown: "카운트다운 설정",
    rotate_servo_popup_stop: "정지",
    id_until: "까지",
    index_back: "뒤로",
    id_blue_disconnect: "Bluetooth가 연결되지 않았습니다",
    touch_tips_error: "현재 블록 ID가 올바르지 않습니다. 삭제하고 재설정하십시오.",
    catLogic: "논리",
    id_sensor_gyroscope: "자이로스코프",
    animal: "동물",
    status: "상태는",
    catMath: "수학",
    recording_cancel: "취소 ",
    speed_M: "중간",
    speed_only_360_value: "현재 장치에 각도 모드 서보가 없습니다.",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "서보 모터의 회전 방향 선택",
    happy: "행복",
    catLoops: "루프",
    id_open_eyes: "눈을 뜨다",
    servo: "서보",
    course_show: "보기",
    id_ok: "확인",
    title_time_adjust: "시간 조정",
    porject_alert_content_01: "아이템 이름이 이미 존재합니다. 다시 입력해주십시오.",
    meebot: "미봇",
    timeout: "최대 실행 반복 초과.",
    project_list_title: "내 프로젝트",
    rotate_servo_popup_clockwise: "시계 방향",
    close_blue: "Bluetooth가 연결되었습니까, 분리되었습니까?",
    wave: "웨이브",
    lion: "사자",
    click: "클릭",
    id_leiguang: "반짝이는 눈물",
    id_lock: "잠금",
    elephant: "코끼리",
    exit_popup_cancel: "취소 ",
    complete: "완전한",
    stop_count: "타이머 중지",
    low_power: "저전력",
    id_dizzy: "어지러움",
    rotate_servo_popup_ok: "확인",
    rotate_servo_popup_cancel: "취소 ",
    httpRequestError: "요청에 문제가 발생하였습니다.",
    y_axie: "피치 각도",
    id_haixiu: "수줍음",
    rhinoceros: "코뿔소",
    id_servo: "서보",
    monkey: "원숭이",
    id_control_repeat_times: "회",
    sound_effects_recording_delete: "삭제",
    reflectance: "반사율",
    angle: "각도",
    id_zhayan: "깜박임",
    id_wink: "깜박임",
    course_hide: "숨기기",
    listVariable: "목록",
    id_yun: "어지러움",
    horse: "말",
    emotion_engine: "엔진",
    project_pop_ok_btn: "확인",
    variable_inputrule_msg: "숫자로 시작할 수 없습니다. 특수 문자를 입력할 수 없습니다. 최대 %1 문자 또는 %2 중국어 문자를 입력할 수 있습니다.",
    id_infinite_loop_error: "메모리가 거의 찼습니다. 되돌린 후 다시 시도하세요.",
    catFunctions: "함수",
    show_count: "타이머 표시",
    let_show_countdown: "Nixie 튜브로 카운트다운 표시",
    id_sensor_touch_sensor: "터치 센서",
    catVariables: "변수",
    id_happy: "즐거움",
    gyro_rotate_direction_popup_ok: "확인",
    posture_ok_desc: "로봇이 동작을 만들고 이름을 부여하도록 설정 ",
    title_setting_emotion: "감정 설정",
    id_sensor_angle: "각도",
    tilt_left: "왼쪽 기울이기",
    no_common_servo_info: "현재 각도 모드 서보(지정된 범위로 회전 가능)가 없습니다. 설정하시겠습니까?",
    id_sensor_touch_sensor_status: "상태",
    id_events: "이벤트",
    exit_tips: "현재 프로그램이 저장되지 않았습니다, 계속하시겠습니까, 종료하시겠습니까?",
    db_click: "더블 클릭",
    delay: "지연",
    touch_tone: "터치톤",
    lose: "잃어버린",
    pig: "돼지",
    id_stop_info: "정지",
    step_1: "단계 1",
    servo_angle: "각도",
    disconnected: "연결 해제됨",
    servo_angle_popup_variable: "변수",
    sysVoiceName: "음성",
    servo_status_popup_adjustable: "잠금 해제",
    id_start_info: "실행",
    movement_gesture: "작동",
    id_shangxin: "슬픔",
    porject_alert_content_05: "죄송합니다, 프로젝트 파일의 프로그램 블록에 오류가 있습니다!",
    speed_VF: "매우 빠름",
    servo_id: "ID",
    add_project_input_check: "16 글자만 입력할 수 있습니다.",
    speed_S: "느림",
    catColour: "색상",
    emotion: "감정",
    press_hold: "홀드 누르기",
    id_sensor_angle_to_zero: "모든 각도를 0으로",
    recording_name_repeat: "기록된 이름 반복",
    ringtones: "벨소리",
    runTooltip: "작업장 블록에 의해 정의된 프로그램 실행",
    servo_mode_error: "서보 모드 오류",
    linkTooltip: "저장 및 블록 연결",
    id_go_to_start: "시작으로 이동",
    ambulance: "구급차",
    tilt_down: "아래로 기울이기",
    yes: "예",
    step_5: "단계 5",
    step_6: "단계 6",
    step_7: "단계 7",
    step_8: "단계 8",
    step_9: "단계 9",
    step_10: "단계 10",
    step_11: "단계 11",
    step_12: "단계 12",
    step_13: "단계 13",
    step_14: "단계 14",
    step_15: "단계 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"노래 1",
    flexin:"노래 2"
    /* 逻辑编程新增歌曲翻译 end*/
};