var MSG = {
    id_all_bright: "wszystko jasne",
    show_countdown: "Pokaż odliczanie",
    porject_alert_content: "Przepraszamy, zły parametr miejsca docelowego. Proszę to sprawdzić!",
    sound_effects_popup_ok: "OK",
    servo_speed: "prędkość",
    gyro_rotate_direction_popup_house: "Kąt pochylenia",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Wprowadzenie klocka",
    servo_angle_popup_close: "Zamknij",
    id_show_show_emoji: "Pokaż emoji",
    exit_popup_title: "Wsk.",
    london_bridge: "Utwór 3",
    step_2: "Krok 2",
    id_degree: "stopnie",
    busy_tone: "Sygnał dźwiękowy zajętości",
    servo_angle_popup_title: "Ustaw kąt obrotu dla silnika siłownika",
    rotate_servo_popup_anti_clockwise: "Lewoskrętny",
    long_lighton: "Zawsze wł.",
    posture_set_desc: "Otwórz prawy przełącznik i ustaw działanie robota",
    recording_alert_ok: "OK",
    porject_alert_content_02: "Błąd operacji usługi podstawowej. Komunikat o błędzie",
    block_error_info: "Błąd istnienia bieżącego klocka, sprawdź go i spróbuj ponownie.",
    sound_effects_popup_cancel: "Anuluj",
    id_close_eyes: "zamknij oczy",
    carhorn1: "Głośnik pojazdu 1",
    id_fengshan: "Wentylator",
    project_has_no_change: "Bieżący program nie uległ zmianie",
    id_sensor_set_gyroscope: "Ustaw żyroskop",
    servo_angle_popup_angle: "Kąt",
    id_show_play_effect: "Odtwórz efekt",
    sound_effects_recording_add: "Dodaj nowe nagranie",
    recording_tips: "Nagrywanie",
    id_control_break: "Out of circulation",
    no_circle_servo_info: "Obecnie brak siłownika w trybie kołowym (może się obracać o 360°). Czy chcesz taki skonfigurować?",
    recording: "nagrywanie",
    run_msg: "Pozwól Jimu poruszać się tak, jak został zaprogramowany przez Ciebie!",
    id_control: "Control",
    variable_named_too_long: "Nazwa projektu nie może przekraczać %1 znaków",
    movements: "ruchy",
    let_show_count: "Pokaż zegar za pom. lampy Nixie",
    id_servos: "Siłowniki obrotu",
    recording_data_tips: "Rekordy: 0",
    title_infrared_sensor: "Ustawienia czujnika podczerwieni",
    add_project_pop_title: "Nazwa projektu",
    step_3: "Krok 3",
    id_rotate: "obrót",
    trashTooltip: "Odrzuć wszystkie klocki.",
    id_smile: "uśmiech",
    id_show_time_during: "przez",
    task: "Misja",
    title_variable_set: "Ustaw zmienną",
    id_control_wait_for: "Wait until",
    z_axie: "Kąt kursu",
    cheerful: "Radosny",
    id_to: "na",
    machine: "urządzenie",
    title_setting_tune: "Ustaw. utworu",
    surprise: "Niespodzianka",
    badCode: "Błąd programu",
    dog: "pies",
    no_project_tip: "Brak projektu, kliknij + w prawym górnym rogu, aby utworzyć projekt!",
    id_daze: "Zszokowany",
    id_sensor_IR_sensor: "Czuj podcz.",
    recording_ok: "OK",
    infrared_tips: "Bieżący model nie jest podłączony do czujnika podczerwieni.",
    swift_msg: "Stuknij tutaj, aby wyświetlić kod swift!",
    id_unlock: "odblokuj",
    see_example: "Wyśw. przykład",
    recording_name_popup_msg: "Nazwa nagrania zawiera nieprawidłowe znaki",
    tiger: "tygrys",
    variable_named_popup_placeholder: "Zmienna",
    id_set: "Ustaw",
    recording_popup_title: "Wprowadzanie nazwy nagranego pliku",
    police_car_1: "Samochód policyjny 1",
    title_setting_light: "Ustaw. światła",
    servo_status_popup_tips: "Nie można wyregulować odpowiadającego siłownika w przypadku robota w trybie zablokowanym",
    help_desc: "Dotknij tutaj, aby wyświetlić wskazówki, gdy wystąpi problem!",
    let_led_scenelight: "Pokaż oświetlenie sceny za pomocą diod LED",
    step_4: "Krok 4",
    posture_named_popup_cancel: "Anuluj",
    id_rotate_circle: "Obrót siłownika 360°",
    id_show: "Pokaż",
    speed_VS: "bardzo wolno",
    porject_alert_content_06: "Projekt zapisany",
    porject_alert_tips: "Porady",
    id_in: "podczas",
    telephone_call: "Rozmowa telefoniczna",
    recording_alert_title: "Błąd",
    ir_sensor: "Czujnik podczerwieni",
    id_sensor_reflectance_between_obstacle: "odbicia od przeszkody",
    btn_name_confirm: "ok",
    id_start: "Start",
    id_show_scenelight: "Pokaż wyświetlacz diodowy",
    add_project_placeholder: "Nazwa projektu",
    id_when_start: "Kliknij „Uruchom”, aby rozpocząć",
    yawn: "Ziewać",
    id_repeat: "Repeat",
    servo_status_popup_ok: "OK",
    sealions: "uchatka",
    gyro_rotate_direction_popup_cancel: "Anuluj",
    blocks: "Klocki",
    release: "Uwolnij",
    posture_link_popup_title: "Model podłączony",
    giraffe: "żyrafa",
    recording_named_too_long: "Nazwa projektu nie może przekraczać %1 znaków",
    title_setting_scenelight: "Skonfiguruj wyświetlacz diodowy",
    touch_sensor: "Czujnik dotykowy",
    catLists: "Listy",
    id_actions: "Ruchy",
    id_custom: "niestandardowy",
    support: "Wsparcie",
    servo_status_popup_title: "Ustaw stan silnika siłownika",
    gyro_rotate_direction_popup_course: "Kąt kursu",
    hashError: "Przepraszamy '%1' nie odnosi się do żadnego zapisanego programu.",
    recording_alert_content: "przyznanie uprawnień nie powiodło się",
    id_huxi: "Oddech",
    shumaguan: "Lampa Nixie",
    cow: "krowa",
    textVariable: "tekst",
    porject_alert_content_03: "Błąd danych otrzymany od podstawy!",
    doorbell: "Dzwonek u drzwi",
    posture_named_popup_ok: "OK",
    axie: "osie",
    show_number: "Pokaż numer",
    let_show_time: "Pokaż czas za pom. lampy Nixie",
    move: "Ruszaj się",
    touch_tips: "Bieżący model nie jest podłączony do czujnika dotykowego.",
    gyroscope_tips: "Bieżący model nie jest podłączony do czujnika żyroskopowego.",
    id_run_to: "Wykonaj",
    project_pop_cancel_btn: "Anuluj",
    tilt_up: "Pochyl w górę",
    show_time: "Pokaż czas",
    posture_link_popup_cancel: "anuluj",
    speed: "prędk.",
    robot: "robot",
    id_cry: "płakać",
    exit_popup_ok: "OK",
    id_jingya: "Zaskoczony",
    id_shanshuo: "Błysk",
    set_servo_mode: "Ustawienia",
    tilt_swing: "Przechylenia obrotowe",
    posture_link: "Model nie jest podłączony. Proszę najpierw połączyć model",
    id_control_wait: "Wait",
    bear: "niedźwiedź",
    select_all: "Cały",
    servo_direction: "kierunek",
    projectlist_msg: "Wyświetl programy, których Jimu się nauczył i które opanował, i stwórz dla niego nowe programy!",
    input_rule_msg: "Nie może zaczynać się od cyfry. Maksymalna dozwolona liczba znaków: %1 (zwykłe) lub %2 (chińskie).",
    lights_tips: "Bieżący model nie jest podłączony do żadnego oświetlenia",
    posture_link_popup_ok: "ok",
    posture_named_popup_title: "Nazwij akcję",
    laser: "Laser",
    newProjectName: "Nowy projekt",
    title_device_tilt: "Ustawienie stanu telefonu/tabletu",
    variable_named_popup_msg: "nazwa zmiennej zawiera niedozwolone znaki",
    x_axie: "Kąt wznosz.",
    recording_title: "Nagrywanie",
    chicken: "kurczak",
    title_bluetooth_connect: "Połącz Bluetooth",
    video_desc: "Dotknij tutaj, aby zobaczyć filmy z opisem zadania!",
    phone_pad: "Telefon/Tablet",
    carhorn: "Głośnik pojazdu",
    id_control_repeat: "Repeat",
    servo_angle_popup_cancel: "Anuluj",
    id_show_play_tune: "Odtwórz utwór",
    let_stop_count: "Zatrz. zegar za pom. lampy Nixie",
    gyro_rotate_direction_popup_horizontal: "Kąt wznoszenia",
    angry: "Zły",
    id_millsecond: "ms",
    badXml: "Błąd parsowania XML",
    gyro_rotate_direction_popup_curVal: "Wartość bieżąca",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Akcja",
    project_name_popup_msg: "Nazwa projektu zawiera nieprawidłowe znaki",
    porject_alert_btnText: "OK",
    id_disco: "Disco",
    id_caise: "Nakładanie kolorów",
    title: "Kod",
    fail: "Niepowodzenie",
    btn_name_cancel: "anuluj",
    yankee_doodle: "Utwór 4",
    snoring: "Chrapanie",
    id_math_not: "Nie",
    doubt: "Pytanie",
    nonsense: "Bredzenie",
    bird: "ptak",
    speed_F: "szybko",
    save_project_msg: "Stuknij tutaj, aby zapisać swój program!",
    actingcute: "Uroczy",
    speed_no_value: "Siłownik bieżącego modelu nie jest wyposażony w tryb obrotu o 360 stopni.",
    recording_placeholder: "Wprowadź nazwę nagrania",
    servo_status_popup_locking: "Zabl.",
    walrus: "mors",
    help_msg: "Stuknij tutaj, jeśli masz jakieś pytania!",
    is_add_project_pop_tips: "Czy zapisać bieżący projekt?",
    servo_angle_popup_ok: "OK",
    catText: "Tekst",
    servo_status_popup_cancel: "Anuluj",
    linkAlert: "Udostępnij bloki za pomocą tego łącza",
    id_sanyuanse: "Kolory podstawowe",
    porject_alert_title: "Błąd",
    id_yugua: "Wycieraczki",
    id_math: "Obliczenia",
    id_relei: "Łzy",
    received: "Otrzymać",
    add_recording_ok: "OK",
    current_value: "wartość bieżąca",
    engine: "Silnik",
    id_deng: "7 kolorowych diod",
    porject_alert_content_04: "Nie udało się odczytać projektu",
    gyroscope: "Żyroskop",
    transfiguration: "Przekształcać",
    id_sad: "Smutny",
    project_name_too_long: "Nazwa projektu nie może przekraczać %1 znaków",
    id_all: "Wsz.",
    posture_named_popup_msg: "Nazwa akcji zawiera niedozwolone znaki",
    title_touch_sensor: "Ustawienia czujnika dotykowego",
    id_moves: "Ruchy",
    id_fadai: "Zszokowany",
    posture_named_too_long: "Nazwa akcji nie może przekraczać %1 znaków",
    sound_effects_popup_title: "Ustaw efekty dźwiękowe",
    rotate_servo_popup_title: "Tryb obracania",
    command: "Rozkaz",
    id_show_show_LEDs: "Pokaż diodami LED",
    id_sensors: "Czujniki",
    let_show_number: "Pokaż numer za pomocą lampy Nixie",
    cover: "Tarcza",
    go_skip: "Pomiń",
    id_show_times: "razy",
    course_tips: "Wyświetlenie niemożliwe!",
    maincontrol_box: "Gł. skrzynka ster.",
    id_while: "While",
    xmlError: "Wczytywanie zapisanego pliku nie powidło się. Być może został stworzony w innej wersji programu Blockly?",
    police_car_2: "Samochód policyjny 2",
    is_add_project_pop_title: "Zapisz projekt",
    tilt_right: "Pochyl w prawo",
    set_countdown: "Ustawienie odliczania",
    rotate_servo_popup_stop: "stop",
    id_until: "Until",
    index_back: "Powr.",
    id_blue_disconnect: "Bluetooth nie jest podłączony",
    touch_tips_error: "Aktualny blok ID nie jest prawidłowe, należy go usunąć i przywrócić",
    catLogic: "Logika",
    id_sensor_gyroscope: "Żyroskop",
    animal: "zwierzę",
    status: "status to",
    catMath: "Obliczenia",
    recording_cancel: "Anuluj",
    speed_M: "średnio",
    speed_only_360_value: "Bieżący sprzęt nie ma siłownika trybu kątowego",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Wybierz kąt obrotu dla silnika siłownika",
    happy: "Szczęśliwy",
    catLoops: "Pętle",
    id_open_eyes: "Otwórz oczy",
    servo: "Siłownik",
    course_show: "Wyśw.",
    id_ok: "OK",
    title_time_adjust: "Koryguj czas",
    porject_alert_content_01: "Nazwa elementu już istnieje. Wprowadź ponownie.",
    meebot: "meebot",
    timeout: "Przekroczono maksymalne wykonywanie iteracji.",
    project_list_title: "Moje projekty",
    rotate_servo_popup_clockwise: "Prawoskr.",
    close_blue: "Bluetooth jest podłączony, czy na pewno odłączyć?",
    wave: "Fala",
    lion: "lew",
    click: "Kliknij",
    id_leiguang: "Błyszczące łzy",
    id_lock: "zablokuj",
    elephant: "słoń",
    exit_popup_cancel: "Anuluj",
    complete: "Kompletny",
    stop_count: "Zatrz. zegar",
    low_power: "Niski poziom zasilania",
    id_dizzy: "Oszołomiony",
    rotate_servo_popup_ok: "OK",
    rotate_servo_popup_cancel: "Anuluj",
    httpRequestError: "Wystąpił problem z żądaniem.",
    y_axie: "Kąt pochylenia",
    id_haixiu: "Nieśmiały",
    rhinoceros: "nosorożec",
    id_servo: "Siłow.",
    monkey: "małpa",
    id_control_repeat_times: "times",
    sound_effects_recording_delete: "Usuń",
    reflectance: "współczynnik odbicia",
    angle: "kąt",
    id_zhayan: "Mruga",
    id_wink: "Mruga",
    course_hide: "Ukryj",
    listVariable: "lista",
    id_yun: "Oszołomiony",
    horse: "koń",
    emotion_engine: "Silnik",
    project_pop_ok_btn: "OK",
    variable_inputrule_msg: "Nie może zaczynać się od cyfry. Nie można wprowadzić specjalnych znaków. Maksymalna dozwolona liczba znaków: %1 (zwykłe) lub %2 (chińskie).",
    id_infinite_loop_error: "Pamięć jest prawie pełna. Wróć, a następnie spróbuj ponownie.",
    catFunctions: "Funkcje",
    show_count: "Pokaż zegar",
    let_show_countdown: "Pokaż odliczanie za pom. lampy Nixie",
    id_sensor_touch_sensor: "Czujnik dotyk.",
    catVariables: "Zmienne",
    id_happy: "Zadowolony",
    gyro_rotate_direction_popup_ok: "OK",
    posture_ok_desc: "Ustaw pozę i nadaj jej nazwę",
    title_setting_emotion: "Ustawienie emocji",
    id_sensor_angle: "kąt",
    tilt_left: "Poch. w lew",
    no_common_servo_info: "Obecnie brak siłownika w trybie kątowym (może się obracać w wyznaczonym zakresie). Czy chcesz taki skonfigurować?",
    id_sensor_touch_sensor_status: "stan",
    id_events: "Zdarzenie",
    exit_tips: "Bieżący program nie zostanie zapisany, czy na pewno zakończyć?",
    db_click: "Podwójne kliknięcie",
    delay: "Opóźnienie",
    touch_tone: "Telefon z klawiaturą",
    lose: "Stracony",
    pig: "świnia",
    id_stop_info: "Stop",
    step_1: "Krok 1",
    servo_angle: "Kąt",
    disconnected: "Niepodłączone",
    servo_angle_popup_variable: "Zmienna",
    sysVoiceName: "głos",
    servo_status_popup_adjustable: "Odblokuj",
    id_start_info: "Uruchom",
    movement_gesture: "Akcja",
    id_shangxin: "Smutny",
    porject_alert_content_05: "Przepraszamy blok programowy w pliku projektu zawiera błędy!",
    speed_VF: "b. szybko",
    servo_id: "ID",
    add_project_input_check: "Można wprowadzić tylko 16 znaków",
    speed_S: "wolno",
    catColour: "Kolor",
    emotion: "Emocja",
    press_hold: "Wciśnij „Zawieś”",
    id_sensor_angle_to_zero: "wszystkie kąty na zero stopni",
    recording_name_repeat: "Powtórz zarejestr. nazwę",
    ringtones: "dzwonki",
    runTooltip: "Uruchom program wg definicji klocków w obszarze roboczym.",
    servo_mode_error: "Błąd trybu siłownika",
    linkTooltip: "Zapisz i połącz z klockami.",
    id_go_to_start: "Wróć",
    ambulance: "Ambulans",
    tilt_down: "Pochyl w dół",
    yes: "tak",
    step_5: "Krok 5",
    step_6: "Krok 6",
    step_7: "Krok 7",
    step_8: "Krok 8",
    step_9: "Krok 9",
    step_10: "Krok 10",
    step_11: "Krok 11",
    step_12: "Krok 12",
    step_13: "Krok 13",
    step_14: "Krok 14",
    step_15: "Krok 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Utwór 1",
    flexin:"Utwór 2"
    /* 逻辑编程新增歌曲翻译 end*/
};