var MSG = {
    id_all_bright: "Radiante",
    show_countdown: "Apres. contagem",
    porject_alert_content: "Parâmetro errado para o alvo operacional. Volte a verificá-lo!",
    sound_effects_popup_ok: "OK",
    servo_speed: "velocidade",
    gyro_rotate_direction_popup_house: "Ângulo de inclinação longitudinal",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Introdução do bloco",
    servo_angle_popup_close: "Fechar",
    id_show_show_emoji: "Mostrar emoji",
    exit_popup_title: "Sugestões",
    london_bridge: "Canção 3",
    step_2: "Passo 2",
    id_degree: "grau",
    busy_tone: "Tom de ocupado",
    servo_angle_popup_title: "Definir ângulo de rotação do servomotor",
    rotate_servo_popup_anti_clockwise: "Para a esquerda",
    long_lighton: "Sempre lig.",
    posture_set_desc: "Abra o comutador direito e defina a ação do robô",
    recording_alert_ok: "OK",
    porject_alert_content_02: "Erro na operação do serviço base. Mensagem de erro",
    block_error_info: "Bloco atual em falha, verifique e tente novamente.",
    sound_effects_popup_cancel: "Cancelar ",
    id_close_eyes: "olhos fechados",
    carhorn1: "Altifalante do veículo 1",
    id_fengshan: "Ventoinha",
    project_has_no_change: "O programa atual não foi alterado",
    id_sensor_set_gyroscope: "Definir giroscópio",
    servo_angle_popup_angle: "Ângulo",
    id_show_play_effect: "Reproduzir efeito",
    sound_effects_recording_add: "Adicionar nova gravação",
    recording_tips: "Gravação",
    id_control_break: "Fora do loop",
    no_circle_servo_info: "Atualmente não existe um servo do modo de roda (pode rodar 360°). Precisa de configurar um agora?",
    recording: "gravação",
    run_msg: "Deixe que o Jimu se mova como o programou!",
    id_control: "Controlo",
    variable_named_too_long: "O nome do projeto não pode exceder %1 caracteres",
    movements: "movimentos",
    let_show_count: "Apres. temp. c/ tubo de Nixie",
    id_servos: "Rodar servos",
    recording_data_tips: "S/ gravações",
    title_infrared_sensor: "Definição do Sensor Infravermelhos",
    add_project_pop_title: "Nome do projeto",
    step_3: "Passo 3",
    id_rotate: "rodar",
    trashTooltip: "Elimine todos os blocos.",
    id_smile: "sorridente",
    id_show_time_during: "por",
    task: "Missão",
    title_variable_set: "Definir Variável",
    id_control_wait_for: "Aguardar até",
    z_axie: "Ângulo de direção",
    cheerful: "Alegre",
    id_to: "e",
    machine: "máquina",
    title_setting_tune: "Ajuste da definição",
    surprise: "Surpresa",
    badCode: "Erro do programa",
    dog: "cão",
    no_project_tip: "Sem projetos. Clicar em + no canto superior direito para criar um!",
    id_daze: "Surpreendido",
    id_sensor_IR_sensor: "Sensor de IV",
    recording_ok: "OK",
    infrared_tips: "O modelo atual não se encontra ligado a um sensor de infravermelhos",
    swift_msg: "Toque aqui para ver o código swift!",
    id_unlock: "desbloquear",
    see_example: "Ver amostra",
    recording_name_popup_msg: "O nome da gravação contém caracteres inválidos",
    tiger: "tigre",
    variable_named_popup_placeholder: "Variável",
    id_set: "Definir",
    recording_popup_title: "Introdução do nome do ficheiro gravada",
    police_car_1: "Carro da polícia 1",
    title_setting_light: "Luz de definição",
    servo_status_popup_tips: "Não é possível ajustar o servomotor correspondente para o robô no modo de bloqueio",
    help_desc: "Toque aqui para ver sugestões úteis quando tiver um problema!",
    let_led_scenelight: "Apres. ilum. de cena c/ luzes LED",
    step_4: "Passo 4",
    posture_named_popup_cancel: "Cancelar ",
    id_rotate_circle: "Rodar servomotor 360°",
    id_show: "Mostrar",
    speed_VS: "muito lenta",
    porject_alert_content_06: "Projeto guardado",
    porject_alert_tips: "Sugestões",
    id_in: "durante",
    telephone_call: "Chamada telefónica",
    recording_alert_title: "Erro",
    ir_sensor: "Sensor de IV",
    id_sensor_reflectance_between_obstacle: "reflectância entre obstáculos",
    btn_name_confirm: "ok",
    id_start: "Iniciar",
    id_show_scenelight: "Apresentar espetáculo de luzes",
    add_project_placeholder: "Nome do projeto",
    id_when_start: "Toque em \"Executar\" para iniciar",
    yawn: "Bocejar",
    id_repeat: "Repetir",
    servo_status_popup_ok: "OK",
    sealions: "leões marinhos",
    gyro_rotate_direction_popup_cancel: "Cancelar ",
    blocks: "Blocos",
    release: "Soltar",
    posture_link_popup_title: "O modelo foi ligado",
    giraffe: "girafa",
    recording_named_too_long: "O nome do projeto não pode exceder %1 caracteres",
    title_setting_scenelight: "Configurar espetáculo de luzes",
    touch_sensor: "Sensor de toque",
    catLists: "Listas",
    id_actions: "Mov.",
    id_custom: "personalizado",
    support: "Suporte",
    servo_status_popup_title: "Definir estado do servomotor",
    gyro_rotate_direction_popup_course: "Ângulo de direção",
    hashError: "\" % 1\" não tem correspondência com qualquer programa guardado.",
    recording_alert_content: "Falha ao conceder privilégios",
    id_huxi: "Respirar",
    shumaguan: "Tubo de Nixie",
    cow: "vaca",
    textVariable: "texto",
    porject_alert_content_03: "Erro nos dados recebidos da base!",
    doorbell: "Campainha",
    posture_named_popup_ok: "OK",
    axie: "eixo",
    show_number: "Apres. número",
    let_show_time: "Apres. hora c/ tubo de Nixie",
    move: "Mover",
    touch_tips: "O modelo atual não se encontra ligado a um sensor tátil",
    gyroscope_tips: "O modelo atual não se encontra ligado a um sensor giroscópio",
    id_run_to: "Executar",
    project_pop_cancel_btn: "Cancelar ",
    tilt_up: "Inclinar para cima",
    show_time: "Apres. hora",
    posture_link_popup_cancel: "cancelar",
    speed: "velocidade",
    robot: "robot",
    id_cry: "choroso",
    exit_popup_ok: "OK",
    id_jingya: "Surpreso",
    id_shanshuo: "Cintilar",
    set_servo_mode: "Configurações",
    tilt_swing: "Inclinar oscilação",
    posture_link: "O modelo não está ligado. Ligue primeiro o modelo",
    id_control_wait: "Aguardar",
    bear: "urso",
    select_all: "Tudo",
    servo_direction: "direção",
    projectlist_msg: "Veja os programas que o Jimu aprendeu e domina e crie novos programas para ele!",
    input_rule_msg: "Não pode começar com um dígito. Pode ser introduzido um máximo de %1 caracteres ou %2 caracteres chineses.",
    lights_tips: "O modelo atual não se encontra ligado a uma luz",
    posture_link_popup_ok: "ok",
    posture_named_popup_title: "Nomeie a ação",
    laser: "Laser",
    newProjectName: "NovoProjeto",
    title_device_tilt: "Defin. do estado do telef./tablet",
    variable_named_popup_msg: "O nome da variável contém caracteres inválidos",
    x_axie: "Ângulo de rotação",
    recording_title: "Gravação",
    chicken: "galinha",
    title_bluetooth_connect: "Ligação Bluetooth",
    video_desc: "Toque aqui para ver vídeos de descrição de tarefa!",
    phone_pad: "Telefone/tablet",
    carhorn: "Altifalante do veículo",
    id_control_repeat: "Repetir",
    servo_angle_popup_cancel: "Cancelar ",
    id_show_play_tune: "Reproduzir melodia",
    let_stop_count: "Parar temp. c/ tubo de Nixie",
    gyro_rotate_direction_popup_horizontal: "Ângulo de rotação",
    angry: "Bravo",
    id_millsecond: "ms",
    badXml: "Erro na análise XML",
    gyro_rotate_direction_popup_curVal: "Valor atual",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Ação",
    project_name_popup_msg: "O nome do projeto contém caracteres inválidos",
    porject_alert_btnText: "OK",
    id_disco: "Disco",
    id_caise: "Empilhamento de cores",
    title: "Código",
    fail: "Falha",
    btn_name_cancel: "cancelar",
    yankee_doodle: "Canção 4",
    snoring: "Ronco",
    id_math_not: "Não",
    doubt: "Questão",
    nonsense: "Delirante",
    bird: "pássaro",
    speed_F: "rápida",
    save_project_msg: "Toque aqui para guardar o seu programa!",
    actingcute: "Fofa",
    speed_no_value: "O servo do modelo atual não contém um modo de rotação de 360 graus.",
    recording_placeholder: "Introduza um nome de gravação",
    servo_status_popup_locking: "Bloquear",
    walrus: "morsa",
    help_msg: "Toque aqui se tiver questões!",
    is_add_project_pop_tips: "Guardar o projeto atual?",
    servo_angle_popup_ok: "OK",
    catText: "Texto",
    servo_status_popup_cancel: "Cancelar ",
    linkAlert: "Partilhe os seus blocos com este link",
    id_sanyuanse: "Cores primárias",
    porject_alert_title: "Erro",
    id_yugua: "Limpadores",
    id_math: "Mat.",
    id_relei: "Lágrimas",
    received: "Receber",
    add_recording_ok: "OK",
    current_value: "valor atual",
    engine: "Motor",
    id_deng: "7 luzes coloridas",
    porject_alert_content_04: "Falha ao ler o projeto",
    gyroscope: "Giroscópio",
    transfiguration: "Transformar",
    id_sad: "Triste",
    project_name_too_long: "O nome do projeto não pode exceder %1 caracteres",
    id_all: "Tudo",
    posture_named_popup_msg: "O nome da ação contém caracteres não permitidos",
    title_touch_sensor: "Definição do sensor de toque",
    id_moves: "Mov.",
    id_fadai: "Surpreendido",
    posture_named_too_long: "O nome da ação não pode exceder os %1 caracteres",
    sound_effects_popup_title: "Definir efeitos de som",
    rotate_servo_popup_title: "Modo de rotação",
    command: "Comando",
    id_show_show_LEDs: "Mostrar LEDs",
    id_sensors: "Sensores",
    let_show_number: "Apres. número c/ tubo de Nixie",
    cover: "Escudo",
    go_skip: "Ignorar",
    id_show_times: "vezes",
    course_tips: "Não pode ser vis. agora!",
    maincontrol_box: "Caixa de controlo principal",
    id_while: "Enquanto",
    xmlError: "Não foi possível carregar o seu ficheiro guardado. Talvez este tenha sido criado com uma versão diferente do Blockly?",
    police_car_2: "Carro da polícia 2",
    is_add_project_pop_title: "Guardar projeto",
    tilt_right: "Inclinar para a direita",
    set_countdown: "Defin. contagem",
    rotate_servo_popup_stop: "Parar",
    id_until: "Até",
    index_back: "Retroceder",
    id_blue_disconnect: "O Bluetooth não está ligado",
    touch_tips_error: "O ID do bloco actual não está correcto, elimine-o e reponha",
    catLogic: "Lógica",
    id_sensor_gyroscope: "Giroscópio",
    animal: "animal",
    status: "o estado é",
    catMath: "Matemática",
    recording_cancel: "Cancelar ",
    speed_M: "média",
    speed_only_360_value: "O equip. atual não contém servo de modo angular",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Selecione a direção de rotação do servomotor",
    happy: "Feliz",
    catLoops: "Ciclos",
    id_open_eyes: "olhos abertos",
    servo: "Servomotor",
    course_show: "Ver",
    id_ok: "OK",
    title_time_adjust: "Ajuste da hora",
    porject_alert_content_01: "O nome do item já existe. Introduza-o novamente.",
    meebot: "meebot",
    timeout: "Limite de iterações de execução excedido.",
    project_list_title: "Os meus projetos",
    rotate_servo_popup_clockwise: "Para a direita",
    close_blue: "O Bluetooth está ligado. Pretende desligá-lo?",
    wave: "Acenar",
    lion: "leão",
    click: "Clicar",
    id_leiguang: "Lágrimas intermitentes",
    id_lock: "bloquear",
    elephant: "elefante",
    exit_popup_cancel: "Cancelar ",
    complete: "Completo",
    stop_count: "Parar temp.",
    low_power: "Baixa potência",
    id_dizzy: "Confuso",
    rotate_servo_popup_ok: "OK",
    rotate_servo_popup_cancel: "Cancelar ",
    httpRequestError: "Ocorreu um problema com o pedido.",
    y_axie: "Ângulo de inclinação longitudinal",
    id_haixiu: "Tímido",
    rhinoceros: "rinoceronte",
    id_servo: "Servomotor",
    monkey: "macaco",
    id_control_repeat_times: "vezes",
    sound_effects_recording_delete: "Eliminar",
    reflectance: "refletância",
    angle: "ângulo",
    id_zhayan: "Piscar",
    id_wink: "Piscar",
    course_hide: "Ocult.",
    listVariable: "lista",
    id_yun: "Confuso",
    horse: "cavalo",
    emotion_engine: "Motor",
    project_pop_ok_btn: "OK",
    variable_inputrule_msg: "Não pode começar com um dígito. Impossível introduzir caracteres especiais. Pode ser introduzido um máximo de %1 caracteres ou %2 caracteres chineses.",
    id_infinite_loop_error: "A memória está quase cheia. Volte atrás e tente novamente",
    catFunctions: "Funções",
    show_count: "Apres. temp.",
    let_show_countdown: "Apres. contagem c/ tubo de Nixie",
    id_sensor_touch_sensor: "Sensor de toque",
    catVariables: "Variáveis",
    id_happy: "Feliz",
    gyro_rotate_direction_popup_ok: "OK",
    posture_ok_desc: "Defina a pose do seu robô para criar uma ação e dê-lhe um nome.",
    title_setting_emotion: "Emoção da definição",
    id_sensor_angle: "ângulo",
    tilt_left: "Inclinar para a esquerda",
    no_common_servo_info: "Atualmente não existe um servo do modo de ângulo (pode dentro de um intervalo designado). Precisa de configurar um agora?",
    id_sensor_touch_sensor_status: "estado",
    id_events: "Eventos",
    exit_tips: "O programa atual não foi guardado. Pretende sair?",
    db_click: "Clicar duas vezes",
    delay: "Atraso",
    touch_tone: "Tom de toque",
    lose: "Perdido",
    pig: "porco",
    id_stop_info: "Parar",
    step_1: "Passo 1",
    servo_angle: "Ângulo",
    disconnected: "Desligado",
    servo_angle_popup_variable: "Variável",
    sysVoiceName: "voz",
    servo_status_popup_adjustable: "Desbloquear",
    id_start_info: "Executar",
    movement_gesture: "Ação",
    id_shangxin: "Triste",
    porject_alert_content_05: "O bloco de programa no ficheiro de projeto contém erros!",
    speed_VF: "muito rápida",
    servo_id: "ID",
    add_project_input_check: "Apenas pode introduzir 16 caracteres",
    speed_S: "lenta",
    catColour: "Cor",
    emotion: "Emoção",
    press_hold: "Premir continuamente",
    id_sensor_angle_to_zero: "todos os ângulos p/ zero graus",
    recording_name_repeat: "Nome gravado repetido",
    ringtones: "toques",
    runTooltip: "Execute o programa definido pelos blocos na área de trabalho.",
    servo_mode_error: "Erro do modo servo",
    linkTooltip: "Guarde e ligue aos blocos.",
    id_go_to_start: "Ir p/ início",
    ambulance: "Ambulância",
    tilt_down: "Inclinar para baixo",
    yes: "sim",
    step_5: "Passo 5",
    step_6: "Passo 6",
    step_7: "Passo 7",
    step_8: "Passo 8",
    step_9: "Passo 9",
    step_10: "Passo 10",
    step_11: "Passo 11",
    step_12: "Passo 12",
    step_13: "Passo 13",
    step_14: "Passo 14",
    step_15: "Passo 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Canção 1",
    flexin:"Canção 2"
    /* 逻辑编程新增歌曲翻译 end*/
};