var MSG = {
    id_all_bright: "все ярко",
    show_countdown: "Показать обратный отсчет",
    porject_alert_content: "Извините, неверный параметр для рабочей цели. Пожалуйста проверьте!",
    sound_effects_popup_ok: "ОК",
    servo_speed: "скорость",
    gyro_rotate_direction_popup_house: "Угол наклона",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Введение блока",
    servo_angle_popup_close: "Закрыть",
    id_show_show_emoji: "Показать эмодзи",
    exit_popup_title: "Советы",
    london_bridge: "Песня 3",
    step_2: "Шаг 2",
    id_degree: "угол",
    busy_tone: "Сигнал «занято»",
    servo_angle_popup_title: "Установить угол вращения сервопривода",
    rotate_servo_popup_anti_clockwise: "Против часовой стрелки",
    long_lighton: "Всегда вкл.",
    posture_set_desc: "Включите правый переключатель и установите действие для робота",
    recording_alert_ok: "ОК",
    porject_alert_content_02: "Ошибка в базовой операции обслуживания. Сообщение ошибки",
    block_error_info: "В текущем блоке имеются проблемы, пожалуйста проверьте и повторите попытку.",
    sound_effects_popup_cancel: "Отмена ",
    id_close_eyes: "закрыть глаза",
    carhorn1: "Динамик транспортного средства 1",
    id_fengshan: "Веер",
    project_has_no_change: "Текущая программа не изменена",
    id_sensor_set_gyroscope: "Установить гироскоп",
    servo_angle_popup_angle: "Угол",
    id_show_play_effect: "Воспроизвести эффект",
    sound_effects_recording_add: "Добавить новую запись",
    recording_tips: "Запись",
    id_control_break: "Выход из цикла",
    no_circle_servo_info: "В настоящий момент нет сервоприводов в режиме колеса (возможность вращения на 360°). Создать?",
    recording: "запись",
    run_msg: "Пусть Jimu двигается так, как вы его запрограммировали!",
    id_control: "Контроль",
    variable_named_too_long: "Длина имени проекта не может превышать %1 символов",
    movements: "движения",
    let_show_count: "Показать таймер на газоразрядном индикаторе",
    id_servos: "Вращать сервоприводы",
    recording_data_tips: "Нет записей",
    title_infrared_sensor: "Настройка инфракрасного датчика",
    add_project_pop_title: "Имя проекта",
    step_3: "Шаг 3",
    id_rotate: "вращать",
    trashTooltip: "Отменить все блоки.",
    id_smile: "улыбка",
    id_show_time_during: "на",
    task: "Миссия",
    title_variable_set: "Задать переменную",
    id_control_wait_for: "Ждать, пока",
    z_axie: "Угол курса",
    cheerful: "радостный",
    id_to: "на",
    machine: "машина",
    title_setting_tune: "Настройка Мелодии",
    surprise: "сюрприз",
    badCode: "Ошибка программы",
    dog: "собака",
    no_project_tip: "Проекты отсутствуют. Нажмите «+» в правом верхнем углу, чтобы создать проект!",
    id_daze: "Изумление",
    id_sensor_IR_sensor: "ИК-датчик",
    recording_ok: "ОК",
    infrared_tips: "Текущая модель не подключена к инфракрасному датчику",
    swift_msg: "Коснитесь здесь для просмотра кода swift!",
    id_unlock: "разблокировать",
    see_example: "Посмотреть пример",
    recording_name_popup_msg: "Имя записи содержит недопустимые символы",
    tiger: "тигр",
    variable_named_popup_placeholder: "Переменная",
    id_set: "Установить",
    recording_popup_title: "Ввод названия записанного файла",
    police_car_1: "Полицейский автомобиль 1",
    title_setting_light: "Настройка Света",
    servo_status_popup_tips: "Невозможно регулировать соответствующий сервопривод для робота в заблокированном режиме",
    help_desc: "Коснитесь здесь, для просмотра полезных советов при возникновении каких-либо проблем!",
    let_led_scenelight: "Показать освещение сцены с помощью светодиодных индикаторов",
    step_4: "Шаг 4",
    posture_named_popup_cancel: "Отмена ",
    id_rotate_circle: "Вращать сервопривод на 360°",
    id_show: "Шоу",
    speed_VS: "очень медленно",
    porject_alert_content_06: "Проект сохранен",
    porject_alert_tips: "Советы",
    id_in: "в течение",
    telephone_call: "Телефонный звонок",
    recording_alert_title: "Ошибка",
    ir_sensor: "ИК-датчик",
    id_sensor_reflectance_between_obstacle: "Расстояние до препятствия",
    btn_name_confirm: "ок",
    id_start: "Пуск",
    id_show_scenelight: "Показать дисплей подсветки",
    add_project_placeholder: "Имя проекта",
    id_when_start: "Щелкните «Запуск» для запуска",
    yawn: "зевать",
    id_repeat: "Повторить",
    servo_status_popup_ok: "ОК",
    sealions: "морские львы",
    gyro_rotate_direction_popup_cancel: "Отмена ",
    blocks: "Блоки",
    release: "Выпустить",
    posture_link_popup_title: "Модель подключена",
    giraffe: "жираф",
    recording_named_too_long: "Длина имени проекта не может превышать %1 символов",
    title_setting_scenelight: "Настроить дисплей подсветки",
    touch_sensor: "Датчик касания",
    catLists: "Списки",
    id_actions: "Движения",
    id_custom: "пользовательская",
    support: "Поддержка",
    servo_status_popup_title: "Установить состояние сервопривода",
    gyro_rotate_direction_popup_course: "Угол курса",
    hashError: "Извините, '%1' не соответствует ни одной сохраненной программе.",
    recording_alert_content: "Сбой предоставления привилегий",
    id_huxi: "Дыхание",
    shumaguan: "Газоразрядный индикатор",
    cow: "корова",
    textVariable: "текст",
    porject_alert_content_03: "Ошибка в данных, полученных из базы!",
    doorbell: "Дверной звонок",
    posture_named_popup_ok: "ОК",
    axie: "ось",
    show_number: "Показать номер",
    let_show_time: "Показать время на газоразрядном индикаторе",
    move: "Переехать",
    touch_tips: "Текущая модель не подключена к датчику касания",
    gyroscope_tips: "Текущая модель не подключена к датчику гироскопа",
    id_run_to: "Выполнять до",
    project_pop_cancel_btn: "Отмена ",
    tilt_up: "Наклон вверх",
    show_time: "Показать время",
    posture_link_popup_cancel: "отмена",
    speed: "скорость",
    robot: "робот",
    id_cry: "плачь",
    exit_popup_ok: "ОК",
    id_jingya: "Удивленный",
    id_shanshuo: "Вспышка",
    set_servo_mode: "Настройки",
    tilt_swing: "Наклон качения",
    posture_link: "Модель не подключена. Сначала подключите модель",
    id_control_wait: "Ожидание",
    bear: "медведь",
    select_all: "Все",
    servo_direction: "направление",
    projectlist_msg: "Просматривайте программы, которые Jimu уже выучил, и создавайте новые программы для него!",
    input_rule_msg: "Не может начинаться с цифры. Можно ввести максимум %1 символов или %2 китайских иероглифов.",
    lights_tips: "Текущая модель не подключена к свету",
    posture_link_popup_ok: "ок",
    posture_named_popup_title: "Назовите действие",
    laser: "Лазер",
    newProjectName: "NewProject",
    title_device_tilt: "Настройка состояния телефона/планшета",
    variable_named_popup_msg: "Имя переменной содержит недопустимые символы",
    x_axie: "Угол вращения",
    recording_title: "Запись",
    chicken: "курица",
    title_bluetooth_connect: "Соединение Bluetooth",
    video_desc: "Коснитесь здесь, чтобы посмотреть видеоролики с описанием задания!",
    phone_pad: "Телефон/планшет",
    carhorn: "Динамик транспортного средства",
    id_control_repeat: "Повторить",
    servo_angle_popup_cancel: "Отмена ",
    id_show_play_tune: "Воспроизвести мелодию",
    let_stop_count: "Остановить таймер на газоразрядном индикаторе",
    gyro_rotate_direction_popup_horizontal: "Угол вращения",
    angry: "Сердитый",
    id_millsecond: "мс",
    badXml: "Ошибка обработки XML",
    gyro_rotate_direction_popup_curVal: "Текущее значение",
    id_show_time_ms: "мс",
    posture_named_popup_placeholder: "Действие",
    project_name_popup_msg: "Имя проекта содержит недопустимые символы",
    porject_alert_btnText: "ОК",
    id_disco: "Disco",
    id_caise: "Многоярусная компоновка цветов",
    title: "Код",
    fail: "недостаточность",
    btn_name_cancel: "отмена",
    yankee_doodle: "Песня 4",
    snoring: "Храп",
    id_math_not: "Не",
    doubt: "Вопрос",
    nonsense: "Raving",
    bird: "птица",
    speed_F: "быстро",
    save_project_msg: "Коснитесь здесь, чтобы сохранить программу!",
    actingcute: "Милый",
    speed_no_value: "Сервопривод текущей модели не оснащен режимом вращения на 360 градусов",
    recording_placeholder: "Введите название записи",
    servo_status_popup_locking: "Заблокировать",
    walrus: "морж",
    help_msg: "Коснитесь здесь, если у вас есть какие-либо вопросы!",
    is_add_project_pop_tips: "Сохранить текущий проект?",
    servo_angle_popup_ok: "ОК",
    catText: "Текст",
    servo_status_popup_cancel: "Отмена ",
    linkAlert: "Поделитесь вашими блоками с помощью этой ссылки",
    id_sanyuanse: "Основные цвета",
    porject_alert_title: "Ошибка",
    id_yugua: "Салфетки",
    id_math: "Матем.",
    id_relei: "Слезы",
    received: "Получать",
    add_recording_ok: "ОК",
    current_value: "текущее значение",
    engine: "Двигатель",
    id_deng: "7 цветных огней",
    porject_alert_content_04: "Не удалось прочитать проект",
    gyroscope: "Гироскоп",
    transfiguration: "преобразование",
    id_sad: "Грустный",
    project_name_too_long: "Длина имени проекта не может превышать %1 символов",
    id_all: "Все",
    posture_named_popup_msg: "Имя действия содержит недопустимые символы",
    title_touch_sensor: "Установка датчика касания",
    id_moves: "Движения",
    id_fadai: "Изумление",
    posture_named_too_long: "Длина имени действия не может превышать %1 символов",
    sound_effects_popup_title: "Установить звуковые эффекты",
    rotate_servo_popup_title: "Режим вращения",
    command: "команда",
    id_show_show_LEDs: "Показать светодиодные индикаторы",
    id_sensors: "Датчики",
    let_show_number: "Показать номер на газоразрядном индикаторе",
    cover: "Щит",
    go_skip: "Пропустить",
    id_show_times: "раз",
    course_tips: "Невозможно отобразить сейчас!",
    maincontrol_box: "Основной блок управления",
    id_while: "По мере того, как",
    xmlError: "Не удалось загрузить ваш сохраненный файл. Возможно он был создан с другой версией Blockly?",
    police_car_2: "Полицейский автомобиль 2",
    is_add_project_pop_title: "Сохранить проект",
    tilt_right: "Наклон вправо",
    set_countdown: "Настройки обратного отсчета",
    rotate_servo_popup_stop: "остановка",
    id_until: "До тех пор, пока",
    index_back: "Назад",
    id_blue_disconnect: "Bluetooth не подключен",
    touch_tips_error: "Текущий блок ID не является правильным, пожалуйста, удалите его и сбросить",
    catLogic: "Логика",
    id_sensor_gyroscope: "Гироскоп",
    animal: "животное",
    status: "состояние",
    catMath: "Математика",
    recording_cancel: "Отмена ",
    speed_M: "средне",
    speed_only_360_value: "Текущее оборудование не имеет сервоприводов в режиме угла",
    id_control_seconds: "мс",
    gyro_rotate_direction_popup_title: "Выберите направление вращения сервопривода",
    happy: "Счастливый",
    catLoops: "Петли",
    id_open_eyes: "Открой глаза",
    servo: "Сервопривод",
    course_show: "Просмотр",
    id_ok: "ОК",
    title_time_adjust: "Регулировка времени",
    porject_alert_content_01: "Название элемента уже существует. Повторите ввод.",
    meebot: "мибот",
    timeout: "Превышено максимальное количество итераций выполнения.",
    project_list_title: "Мои проекты",
    rotate_servo_popup_clockwise: "По часовой стрелке",
    close_blue: "Bluetooth подключен, отключить?",
    wave: "Волна",
    lion: "лев",
    click: "Щелчок",
    id_leiguang: "Кратковременные слезы",
    id_lock: "заблокировать",
    elephant: "слон",
    exit_popup_cancel: "Отмена ",
    complete: "полный",
    stop_count: "Остановить таймер",
    low_power: "Низкий уровень заряда",
    id_dizzy: "Головокружение",
    rotate_servo_popup_ok: "ОК",
    rotate_servo_popup_cancel: "Отмена ",
    httpRequestError: "Возникла проблема с запросом.",
    y_axie: "Угол наклона",
    id_haixiu: "Робкий",
    rhinoceros: "носорог",
    id_servo: "Сервопривод",
    monkey: "обезьяна",
    id_control_repeat_times: "раз",
    sound_effects_recording_delete: "Удалить",
    reflectance: "коэффициент отражения",
    angle: "градус",
    id_zhayan: "Мигание",
    id_wink: "Мигание",
    course_hide: "Скрыть",
    listVariable: "список",
    id_yun: "Головокружение",
    horse: "лошадь",
    emotion_engine: "двигатель",
    project_pop_ok_btn: "ОК",
    variable_inputrule_msg: "Не может начинаться с цифры. Нельзя вводить специальные символы. Можно ввести максимум %1 символов или %2 китайских иероглифов.",
    id_infinite_loop_error: "Память заполнена практически полностью, повторите попытку после возврата",
    catFunctions: "Функции",
    show_count: "Показать таймер",
    let_show_countdown: "Показать обратный отсчет на газоразрядном индикаторе",
    id_sensor_touch_sensor: "Датчик касания",
    catVariables: "Переменные",
    id_happy: "Счастливый",
    gyro_rotate_direction_popup_ok: "ОК",
    posture_ok_desc: "Установите позу и введите ее название",
    title_setting_emotion: "Настройка Эмоции",
    id_sensor_angle: "угол",
    tilt_left: "Наклон влево",
    no_common_servo_info: "В настоящий момент нет сервоприводов в режиме угла (возможность поворота на заданный угол). Создать?",
    id_sensor_touch_sensor_status: "состояние",
    id_events: "События",
    exit_tips: "Текущая программа не сохранена, продолжить выход？",
    db_click: "Двойной щелчок",
    delay: "задержка",
    touch_tone: "Звук касания",
    lose: "Потерял",
    pig: "свинья",
    id_stop_info: "Остановка",
    step_1: "Шаг 1",
    servo_angle: "Угол",
    disconnected: "Отключено",
    servo_angle_popup_variable: "Переменная",
    sysVoiceName: "голос",
    servo_status_popup_adjustable: "Разблокировать",
    id_start_info: "Запуск",
    movement_gesture: "Действие",
    id_shangxin: "Грустный",
    porject_alert_content_05: "Извините, блок программы в файле проекта содержит ошибки!",
    speed_VF: "очень быстро",
    servo_id: "ID",
    add_project_input_check: "Можно ввести только 16 символов",
    speed_S: "медленно",
    catColour: "Цвет",
    emotion: "эмоция",
    press_hold: "Нажмите Hold",
    id_sensor_angle_to_zero: "все углы на ноль градусов",
    recording_name_repeat: "Повтор названия записи",
    ringtones: "мелодии звонка",
    runTooltip: "Запустите программу, заданную блоками в рабочей области.",
    servo_mode_error: "Ошибка режима сервопривода",
    linkTooltip: "Сохраните и свяжите с блоками.",
    id_go_to_start: "Перейти в начало",
    ambulance: "Cкорая помощь",
    tilt_down: "Наклон вниз",
    yes: "да",
    step_5: "Шаг 5",
    step_6: "Шаг 6",
    step_7: "Шаг 7",
    step_8: "Шаг 8",
    step_9: "Шаг 9",
    step_10: "Шаг 10",
    step_11: "Шаг 11",
    step_12: "Шаг 12",
    step_13: "Шаг 13",
    step_14: "Шаг 14",
    step_15: "Шаг 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Песня 1",
    flexin:"Песня 2"
    /* 逻辑编程新增歌曲翻译 end*/
};