var MSG = {
    id_all_bright: "Tümü aydınlk",
    show_countdown: "Geri sayımı göster",
    porject_alert_content: "Üzgünüm, çalışan hedef için yanlış parametre. Lütfen kontrol edin!",
    sound_effects_popup_ok: "Tamam",
    servo_speed: "hız",
    gyro_rotate_direction_popup_house: "Adım açısı",
    id_math_variables_set_add: "%1 + %2",
    help_title: "Blok tanıtımı",
    servo_angle_popup_close: "Kapat",
    id_show_show_emoji: "Emoji göster",
    exit_popup_title: "İpucu",
    london_bridge: "Şarkı 3",
    step_2: "Adım 2",
    id_degree: "derece",
    busy_tone: "Meşgul tonu",
    servo_angle_popup_title: "Servo motorunun dönme açısını ayarlayın",
    rotate_servo_popup_anti_clockwise: "Saat yönü tersine",
    long_lighton: "Her zaman açık",
    posture_set_desc: "Sağ anahtarı açın ve robotun eylemini ayarlayın",
    recording_alert_ok: "Tamam",
    porject_alert_content_02: "Taban hizmetlerinin çalıştırılmasında hata. Hata mesajı",
    block_error_info: "Mevcut blokta hata var, lütfen kontrol edip tekrar deneyin.",
    sound_effects_popup_cancel: "İptal",
    id_close_eyes: "gözleri kapa",
    carhorn1: "Araç hoparlörü 1",
    id_fengshan: "Fan",
    project_has_no_change: "Mevcut program değiştirilmemiş",
    id_sensor_set_gyroscope: "Cayroskop ayarla",
    servo_angle_popup_angle: "Açı",
    id_show_play_effect: "Efekt oynat",
    sound_effects_recording_add: "Yeni kayıt ekle",
    recording_tips: "Kaydedliyor",
    id_control_break: "Devre dışı",
    no_circle_servo_info: "Şu anda servo tekerlek modu yok (360 ° döndürebiliyorsunuz). Bir tane ayarlamanız gerekiyor mu?",
    recording: "Kaydedliyor",
    run_msg: "Jimu'yu programladıkça hareket etsin!",
    id_control: "Kontrol",
    variable_named_too_long: "Proje adı %1 karakteri aşamaz",
    movements: "hareketler",
    let_show_count: "Nixie tüpüyle zamanlayıcı göster",
    id_servos: "Servoları döndür",
    recording_data_tips: "Kayıt yok",
    title_infrared_sensor: "Kızılötesi Sensör Ayarı",
    add_project_pop_title: "Proje adı",
    step_3: "Adım 3",
    id_rotate: "döndür",
    trashTooltip: "Tüm blokları at.",
    id_smile: "gül",
    id_show_time_during: "için",
    task: "Görev",
    title_variable_set: "Değişken Ayarla",
    id_control_wait_for: "Kadar bekle",
    z_axie: "Gittiği açı",
    cheerful: "Neşeli",
    id_to: "-e",
    machine: "Makine",
    title_setting_tune: "Ses Ayarlanıyor",
    surprise: "Sürpriz",
    badCode: "Program hatası",
    dog: "Köpk",
    no_project_tip: "Hiçbir proje yoksa, sağ üst köşedeki + simgesini tıklayın!",
    id_daze: "Büyülenmiş",
    id_sensor_IR_sensor: "KÖ sensör",
    recording_ok: "Tmm",
    infrared_tips: "Mevcut model bir kızıl ötesi algılayıcıya bağlı değil",
    swift_msg: "Swift kodu görüntülemek için buraya tıklayın!",
    id_unlock: "kilit aç",
    see_example: "Örneği gör",
    recording_name_popup_msg: "Kayıt adı geçersiz karakterler içeriyor",
    tiger: "Kaplan",
    variable_named_popup_placeholder: "Değişken",
    id_set: "Ayar",
    recording_popup_title: "Kaydedilen dosya adı girişi",
    police_car_1: "Polis arabası 1",
    title_setting_light: "Işık Ayarlanıyor",
    servo_status_popup_tips: "Kilitli moddayken robotun ilgili servosunu ayarlayamazsınız",
    help_desc: "Bir sorunla karşılaştığında faydalı ipucu görmek için tıkla!",
    let_led_scenelight: "LED ışıkları ile sahne aydınlatmasını gösterin",
    step_4: "Adım 4",
    posture_named_popup_cancel: "İptal",
    id_rotate_circle: "Servoyu 360° döndür",
    id_show: "Göst.",
    speed_VS: "çok yavaş",
    porject_alert_content_06: "Proje kaydedildi",
    porject_alert_tips: "İpucu",
    id_in: "sırada",
    telephone_call: "Telefon araması",
    recording_alert_title: "Hata",
    ir_sensor: "KÖ Sensör",
    id_sensor_reflectance_between_obstacle: "Engele uzaklığı",
    btn_name_confirm: "tmm",
    id_start: "Başlat",
    id_show_scenelight: "Işık Ekranını Göster",
    add_project_placeholder: "Proje adı",
    id_when_start: "Başlmk için 'Git'e tıkla",
    yawn: "Esneme",
    id_repeat: "Tekrarla",
    servo_status_popup_ok: "Tamam",
    sealions: "Dnz aslan.",
    gyro_rotate_direction_popup_cancel: "İptal",
    blocks: "Bloklar",
    release: "Bırak",
    posture_link_popup_title: "Model bağlı",
    giraffe: "Zürafa",
    recording_named_too_long: "Proje adı %1 karakteri aşamaz",
    title_setting_scenelight: "Işık Ekranını Kur",
    touch_sensor: "Doknmtk. Sensör",
    catLists: "List.",
    id_actions: "Hamle.",
    id_custom: "özel",
    support: "Destek",
    servo_status_popup_title: "Servo motoru durumunu ayarla",
    gyro_rotate_direction_popup_course: "Gittiği açı",
    hashError: "Özür dileriz ‘%1’ hiçbir kayıtlı programa karşılık gelmiyor.",
    recording_alert_content: "ayrıcalık verilme başarısız",
    id_huxi: "Nefes Al",
    shumaguan: "Dijital Tüp",
    cow: "İnek",
    textVariable: "metin",
    porject_alert_content_03: "Tabandan alınan veride hata!",
    doorbell: "Kapı zili",
    posture_named_popup_ok: "Tamam",
    axie: "eksen",
    show_number: "Numarayı göster",
    let_show_time: "Nixie tüpüyle zamanı göster",
    move: "Hareket Etmek",
    touch_tips: "Mevcut model dokunmatik sensöre bağlı değil",
    gyroscope_tips: "Mevcut model bir jiroskop sensörüne bağlı değil",
    id_run_to: "Yürüt",
    project_pop_cancel_btn: "İptal",
    tilt_up: "Yukarı eğ",
    show_time: "Zamanı göster",
    posture_link_popup_cancel: "iptal et",
    speed: "hız",
    robot: "Robot",
    id_cry: "ağla",
    exit_popup_ok: "Tamam",
    id_jingya: "Şaşırmış",
    id_shanshuo: "Flaş",
    set_servo_mode: "Ayarlar",
    tilt_swing: "Sallayark eğ",
    posture_link: "Model bağlı değil. Lütfen önce modeli bağlayın",
    id_control_wait: "Bekle",
    bear: "Ayı",
    select_all: "Hepsini Seç",
    servo_direction: "yön",
    projectlist_msg: "Jimu'nun öğrendiği ve hakim olduğu programları görün ve bunun için yeni programlar oluşturun!",
    input_rule_msg: "Bir rakam ile başlayamaz. Maksimum %1 veya %2 Çince karakter girilebilir.",
    lights_tips: "Mevcut model hiçbir ışığa bağlı değil",
    posture_link_popup_ok: "tmm",
    posture_named_popup_title: "Eyleme ad ver",
    laser: "Lazer",
    newProjectName: "YeniProje",
    title_device_tilt: "Telefon/Tablet durum ayarı",
    variable_named_popup_msg: "değişken adı izin verilmeyen karakterler içeriyor",
    x_axie: "Yuvar. açısı",
    recording_title: "Kaydedliyor",
    chicken: "Tavuk",
    title_bluetooth_connect: "Bluetooth Bağlantısı",
    video_desc: "Görev tarifi videolarına bakmak için buraya tıklayın!",
    phone_pad: "Telefon/Tablet",
    carhorn: "Araç hoparlörü",
    id_control_repeat: "Tekrarla",
    servo_angle_popup_cancel: "İptal",
    id_show_play_tune: "Ses oynat",
    let_stop_count: "Nixie tüpüyle zamanlayıcıyı durdurun",
    gyro_rotate_direction_popup_horizontal: "Yuvar. açısı",
    angry: "Kızgın",
    id_millsecond: "ms",
    badXml: "Hata ayırma XML",
    gyro_rotate_direction_popup_curVal: "Mevcut değer",
    id_show_time_ms: "ms",
    posture_named_popup_placeholder: "Eylem",
    project_name_popup_msg: "Proje adı izin geçersiz karakterler içeriyor",
    porject_alert_btnText: "Tamam",
    id_disco: "Disco",
    id_caise: "Renk Yığınlama",
    title: "Kod",
    fail: "Başarısızlık",
    btn_name_cancel: "iptal et",
    yankee_doodle: "Şarkı 4",
    snoring: "Horlama",
    id_math_not: "Yok",
    doubt: "Soru",
    nonsense: "Çılgın",
    bird: "Kuş",
    speed_F: "hızlı",
    save_project_msg: "Programınızı kaydetmek için buraya dokunun!",
    actingcute: "Sevimli",
    speed_no_value: "Mevcut modelin servosu 360° dönme modunu kapsamıyor",
    recording_placeholder: "Lütfen bir kayıt adı girin",
    servo_status_popup_locking: "Kilit",
    walrus: "Mors",
    help_msg: "Herhangi bir sorunuz varsa buraya dokunun!",
    is_add_project_pop_tips: "Mevcut proje kayd. mi?",
    servo_angle_popup_ok: "Tamam",
    catText: "Metin",
    servo_status_popup_cancel: "İptal",
    linkAlert: "Bloklarınızı bu bağlantıyla paylaşın",
    id_sanyuanse: "Ana Renkler",
    porject_alert_title: "Hata",
    id_yugua: "Silecekler",
    id_math: "Mat.",
    id_relei: "Gözyaşları",
    received: "Alma",
    add_recording_ok: "Tmm",
    current_value: "mevcut değer",
    engine: "Motor",
    id_deng: "7 renkli ışıklar",
    porject_alert_content_04: "Proje okunamadı",
    gyroscope: "Cayroskop",
    transfiguration: "Dönüşme",
    id_sad: "Üzgün",
    project_name_too_long: "Proje adı %1 karakteri aşamaz",
    id_all: "Tümü",
    posture_named_popup_msg: "Eylem adı izin verilmeyen karakterler içeriyor",
    title_touch_sensor: "Dokunmatik sensör ayarı",
    id_moves: "Hamle.",
    id_fadai: "Büyülenmiş",
    posture_named_too_long: "Eylem adı %1 karakteri aşamaz",
    sound_effects_popup_title: "Ses efekt. ayarla",
    rotate_servo_popup_title: "Dönme Modu",
    command: "Emir",
    id_show_show_LEDs: "LED göster",
    id_sensors: "Sensörler",
    let_show_number: "Nixie tüpüyle numarayı göster",
    cover: "Kalkan",
    go_skip: "Geç",
    id_show_times: "kez",
    course_tips: "Şimdi görülemiyor!",
    maincontrol_box: "Ana kontrol kutusu",
    id_while: "Sırada",
    xmlError: "Kaydedilen dosyanız yüklenemedi. Blockly’nin başka bir versiyonuyla kaydedilmiş olabilir mi?",
    police_car_2: "Polis arabası 2",
    is_add_project_pop_title: "Projeyi kaydet",
    tilt_right: "Sağa eğ",
    set_countdown: "Geri sayım ayarı",
    rotate_servo_popup_stop: "dur",
    id_until: "Kadar",
    index_back: "Geri",
    id_blue_disconnect: "Bluetooth bağlı değil",
    touch_tips_error: "Geçerli blok kimliği doğru değil, lütfen silin ve sıfırlayın",
    catLogic: "Mantık",
    id_sensor_gyroscope: "Cayroskop",
    animal: "Hayvan",
    status: "durum",
    catMath: "Mat.",
    recording_cancel: "İptal",
    speed_M: "orta",
    speed_only_360_value: "Mevcut ekipmanda açı modu servosu yok",
    id_control_seconds: "ms",
    gyro_rotate_direction_popup_title: "Servo motorunun dönme yönünü ayarlayın",
    happy: "Mutlu",
    catLoops: "Döngü.",
    id_open_eyes: "açık gözler",
    servo: "Servo",
    course_show: "Göst.",
    id_ok: "Tamam",
    title_time_adjust: "Zaman Ayarı",
    porject_alert_content_01: "Öge adı zaten mevcut. Lütfen tekrar girin.",
    meebot: "meebot",
    timeout: "Maksimum yürütme tekrarı aşıldı.",
    project_list_title: "Projelerim",
    rotate_servo_popup_clockwise: "Saat yönüne",
    close_blue: "Bluetooth bağlı, kesilsin mi?",
    wave: "Dalga",
    lion: "Aslan",
    click: "Tıkla",
    id_leiguang: "Yanıp sönen Gözyaşları",
    id_lock: "kilit",
    elephant: "Fil",
    exit_popup_cancel: "İptal",
    complete: "Tam",
    stop_count: "Zamanlayıcıyı Durdur",
    low_power: "Düşük güç",
    id_dizzy: "Sersemlemiş",
    rotate_servo_popup_ok: "Tamam",
    rotate_servo_popup_cancel: "İptal",
    httpRequestError: "İstekle ilgili bir sorun çıktı.",
    y_axie: "Adım açısı",
    id_haixiu: "Utangaç",
    rhinoceros: "Gergedan",
    id_servo: "Servo",
    monkey: "Maymun",
    id_control_repeat_times: "kez",
    sound_effects_recording_delete: "Sil",
    reflectance: "yansıtıcılık",
    angle: "açı",
    id_zhayan: "Göz Kırp",
    id_wink: "Göz Kırp",
    course_hide: "Sakla",
    listVariable: "liste",
    id_yun: "Sersemlemiş",
    horse: "At",
    emotion_engine: "Motor",
    project_pop_ok_btn: "Tamam",
    variable_inputrule_msg: "Bir rakam ile başlayamaz. Özel karakterler girilemez. Maksimum %1 veya %2 Çince karakter girilebilir.",
    id_infinite_loop_error: "Bellek neredeyse dolu, geri döndükten sonra tekrar deneyin.",
    catFunctions: "İşlevler",
    show_count: "Zamanlayıcıyı göster",
    let_show_countdown: "Nixie tüpüyle geri sayımı göster",
    id_sensor_touch_sensor: "Doknmtk. sensör",
    catVariables: "Değişkenler",
    id_happy: "Mutlu",
    gyro_rotate_direction_popup_ok: "Tamam",
    posture_ok_desc: "Bir eylem oluşturmak için, robotuna bir duruş ayarla ve ona bir isim ver.",
    title_setting_emotion: "Duygu Ayarlanıyor",
    id_sensor_angle: "açı",
    tilt_left: "Sola eğ",
    no_common_servo_info: "Halen açılı mod servo yok (belirlenmiş bir aralıkta dönüş yapabiliyor). Bir tane ayarlamanız gerekiyor mu?",
    id_sensor_touch_sensor_status: "durum",
    id_events: "Olaylar",
    exit_tips: "Mevcut program kaydedilmemiş, çıkmaya devam edilsin mi ?",
    db_click: "Çift Tıkla",
    delay: "Gecikme",
    touch_tone: "Dokunma tonu",
    lose: "Kayıp",
    pig: "Domz",
    id_stop_info: "Dur",
    step_1: "Adım 1",
    servo_angle: "Açı",
    disconnected: "Bağlantı koptu",
    servo_angle_popup_variable: "Değişken",
    sysVoiceName: "ses",
    servo_status_popup_adjustable: "Kilit Aç",
    id_start_info: "Git",
    movement_gesture: "Eylem",
    id_shangxin: "Üzgün",
    porject_alert_content_05: "Üzgünüm, Proje dosyasındaki program bloğu hatalar içeriyor!",
    speed_VF: "çok hızlı",
    servo_id: "ID",
    add_project_input_check: "Yalnızca 16 karakter girilebilir",
    speed_S: "yavaş",
    catColour: "Renk",
    emotion: "Duygu",
    press_hold: "Basılı Tut",
    id_sensor_angle_to_zero: "tüm açılar sıfır dereceye",
    recording_name_repeat: "Kaydedilen Adı Tekrarla",
    ringtones: "Zil sesleri",
    runTooltip: "Çalışma alanında bloklarla tanımlanan programı çalıştırın.",
    servo_mode_error: "Servo Modu Hatası",
    linkTooltip: "Kaydet ve bloklara bağla.",
    id_go_to_start: "Başlata gidin",
    ambulance: "Ambulans",
    tilt_down: "Aşağı eğ",
    yes: "Evet",
    step_5: "Adım 5",
    step_6: "Adım 6",
    step_7: "Adım 7",
    step_8: "Adım 8",
    step_9: "Adım 9",
    step_10: "Adım 10",
    step_11: "Adım 11",
    step_12: "Adım 12",
    step_13: "Adım 13",
    step_14: "Adım 14",
    step_15: "Adım 15",
    /* 逻辑编程新增歌曲翻译 begin   london_bridge-3  yankee_doodle-4*/
    come_and_play:"Şarkı 1",
    flexin:"Şarkı 2"
    /* 逻辑编程新增歌曲翻译 end*/
};